### ISSUE TITLE
group rdn with leading space char and add fails error 21 invalid syntax and delete fails error 32

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4383]
Ticket was cloned from Red Hat Bugzilla (product _Red Hat Enterprise Linux 8_): [Bug 1888863](https://bugzilla.redhat.com/show_bug.cgi?id=1888863)

```
Description of problem:

deleting the DN of a group fails if there is a leading space char in the RDN
fails with error 32

user entries have a valid DN syntax with

dn: uid=\ leadingspaceuser1,cn=users,dc=example,dc=test
dn: uid=\20leadingspaceuser1,cn=users,dc=example,dc=test

dn: cn=\ leadingspaceuser1,cn=users,dc=example,dc=test
dn: cn=\20leadingspaceuser1,cn=users,dc=example,dc=test


but group DNs have a different behavior:

dn: cn=\ specialgroupname1,cn=groups,dc=example,dc=test
dn: cn=\20specialgroupname1,cn=groups,dc=example,dc=test

then, if such a group is in the database, it cannot be deleted, there is an
error 32

why do the special chars cannot be escaped for groups?


Version-Release number of selected component (if applicable):
RHEL-8.2
389-ds-base-1.4.x

but same on any versions of 389-ds-base


How reproducible:
on demand

Steps to Reproduce:
1. have some data

echo \ specialgroupname1 | base64
IHNwZWNpYWxncm91cG5hbWUxCg==

echo IHNwZWNpYWxncm91cG5hbWUxCg== | base64 -d
 specialgroupname1

cat << EOF > ~/dn.group.cn.with.leading.space.cn.users.ldif
dn: cn=users,dc=example,dc=test
objectClass: top
objectClass: nsContainer
cn: users

dn: uid=user1,cn=users,dc=example,dc=test
givenName: Test
sn: User1
uid: user1
cn: Test User1
displayName: Test User1
initials: TU
gecos: Test User1
homeDirectory: /home/user1
uidNumber: 969400001
gidNumber: 969400001
objectClass: person
objectClass: organizationalperson
objectClass: posixaccount
objectClass: inetorgperson
objectClass: inetuser

dn: uid=user2,cn=users,dc=example,dc=test
givenName: Test
sn: User2
uid: user2
cn: Test User2
displayName: Test User2
initials: TU
gecos: Test User2
homeDirectory: /home/user2
uidNumber: 969400002
gidNumber: 969400002
objectClass: person
objectClass: organizationalperson
objectClass: posixaccount
objectClass: inetorgperson
objectClass: inetuser

dn: cn=groups,dc=example,dc=test
objectClass: top
objectClass: nsContainer
cn: groups

dn: cn=\ specialgroupname1,cn=groups,dc=example,dc=test
objectClass: groupofnames
cn:: IHNwZWNpYWxncm91cG5hbWUxCg==
description:  cn with a space header char in string
member: uid=user1,cn=users,dc=example,dc=test
member: uid=user2,cn=users,dc=example,dc=test
EOF

sed -i 's/[[:space:]]*$//' ~/cn.with.a.spacegroupname.cn.groupss.ldif


2. attempt to create the goupr DN with a leading char in RDN

ldapmodify -xD "cn=directory manager" -w password -caf
~/dn.group.cn.with.leading.space.cn.users.ldif



Actual results:

adding new entry "cn=\ specialgroupname1,cn=groups,dc=example,dc=test"
ldap_add: Invalid syntax (21)

adding new entry "cn=\20specialgroupname1,cn=groups,dc=example,dc=test"
ldap_add: Invalid DN syntax (34)
        additional info: DN value invalid per syntax


Expected results:
yes


Additional info:
was reported on RHEL-6 / RHDS-9 by a customer.
```

**Comment by mreynolds389** [comment]
For future reference...

These stack traces below are where the index gets corrupted when a value with a escaped space is already normalized, but needs to be added to the index.   What happens is that when we add "uid=\20mark,ou=people,dc=example,dc=com", it wants to create two "uid" attributes in the entry (index_addordel_values_ext_sv):  "\ mark" and " mark", but when we add " mark" to the index it gets normalized again to "mark".  Right now there is no obvious way to know if " mark" was already normalized or not.

This is the code where the values get normalized a second time:

```
#0  string_values2keys (pb=0x7fa982dff060, bvals=0x7fa986609640, ivals=0x7fa98ddfd290, syntax=1, ftype=163) at ../389-ds-base/ldap/servers/plugins/syntaxes/string.c:411
#1  0x00007fa9dfb63ec9 in cis_values2keys (pb=0x7fa982dff060, vals=0x7fa986609640, ivals=0x7fa98ddfd290, ftype=163)
    at ../389-ds-base/ldap/servers/plugins/syntaxes/cis.c:786
#2  0x00007fa9e0e38922 in slapi_attr_values2keys_sv_pb (sattr=0x7fa9df6470b0, vals=0x7fa986609640, ivals=0x7fa98ddfd290, ftype=163, pb=0x7fa982dff060)
    at ../389-ds-base/ldap/servers/slapd/plugin_syntax.c:628
#3  0x00007fa9e0e38996 in slapi_attr_values2keys_sv (sattr=0x7fa9df6470b0, vals=0x7fa986609640, ivals=0x7fa98ddfd290, ftype=163)
    at ../389-ds-base/ldap/servers/slapd/plugin_syntax.c:646
#4  0x00007fa9dc4a6539 in index_addordel_values_ext_sv (be=0x7fa9df6ec180, type=0x7fa988a0b0e0 "uid", vals=0x7fa986609640, evals=0x0, id=3, flags=17, txn=0x0, 
    idl_disposition=0x7fa98ddfd420, buffer_handle=0x0) at ../389-ds-base/ldap/servers/slapd/back-ldbm/index.c:2075
#5  0x00007fa9dc511c2d in import_worker (param=0x7fa988a23820) at ../389-ds-base/ldap/servers/slapd/back-ldbm/db-bdb/bdb_import_threads.c:2995
#6  0x00007fa9e0903554 in _pt_root () from target:/lib64/libnspr4.so
#7  0x00007fa9e0897432 in start_thread () from target:/lib64/libpthread.so.0
#8  0x00007fa9e06b3913 in clone () from target:/lib64/libc.so.6

or

#0  string_values2keys (pb=0x7fa982dff060, bvals=0x7fa986609640, ivals=0x7fa98ddfd290, syntax=1, ftype=163) at ../389-ds-base/ldap/servers/plugins/syntaxes/string.c:411
#1  0x00007fa9dfb63ec9 in cis_values2keys (pb=0x7fa982dff060, vals=0x7fa986609640, ivals=0x7fa98ddfd290, ftype=163)
    at ../389-ds-base/ldap/servers/plugins/syntaxes/cis.c:786
#2   slapi_attr_values2keys_sv (sattr=0x7f9c42a470b0, vals=0x7f9c3fb03e60, ivals=0x7f9be63fc950, ftype=163) at ../389-ds-base/ldap/servers/slapd/plugin_syntax.c:646
#4  0x00007f9c3f8a6493 in index_addordel_values_ext_sv (be=0x7f9c3faa2e00, type=0x7f9c3fa02f50 "uid", vals=0x7f9c3fb03e60, evals=0x0, id=7, flags=1, txn=0x7f9be63fccc0, idl_disposition=0x0, 
    buffer_handle=0x0) at ../389-ds-base/ldap/servers/slapd/back-ldbm/index.c:2066
#5  0x00007f9c3f8a619e in index_addordel_values_sv (be=0x7f9c3faa2e00, type=0x7f9c3fa02f50 "uid", vals=0x7f9c3fb03e60, evals=0x0, id=7, flags=1, txn=0x7f9be63fccc0)
    at ../389-ds-base/ldap/servers/slapd/back-ldbm/index.c:1993
#6  0x00007f9c3f8a1dad in index_addordel_entry (be=0x7f9c3faa2e00, e=0x7f9c42ae62f0, flags=1, txn=0x7f9be63fccc0) at ../389-ds-base/ldap/servers/slapd/back-ldbm/index.c:462
#7  0x00007f9c3f8ab366 in ldbm_back_add (pb=0x7f9c3f9ac920) at ../389-ds-base/ldap/servers/slapd/back-ldbm/ldbm_add.c:1051
```

This needs to be looked at via a new ticket, but I wanted to record these findings, while the issue in the ticket is still being addressed (PR coming soon)...

**Comment by mreynolds389** [comment]
6233c0415..5376f5520  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
97bf1fa34..2096f3430  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
d2f2e5074..8ce1c5d2b  389-ds-base-1.4.2 -> 389-ds-base-1.4.2
