### ISSUE TITLE
SIGFPE crash in rhds disk monitoring routine

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4413]
Ticket was cloned from Red Hat Bugzilla (product _Red Hat Enterprise Linux 8_): [Bug 1890118](https://bugzilla.redhat.com/show_bug.cgi?id=1890118)

```
Description of problem:

A customer reports a crash in RHDS that occurs every day at same time

Version-Release number of selected component (if applicable):

RHDS 11

How reproducible:

Not reproduced in-house. Happens regularly on customer site

Actual results:

Crash happening every morning around 5am

Expected results:

RHDS should not crash

Additional info:

This is the stackframe of the crash, I will attach the core file as well

Core was generated by `/usr/sbin/ns-slapd -D /etc/dirsrv/slapd-ul -i /run/dirsrv/slapd-ul.pid'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x000055c19b7fd48f in monitor_disk_info ()
[Current thread is 1 (Thread 0x7f8605bfe700 (LWP 1956012))]

Thread 1 (Thread 0x7f8605bfe700 (LWP 1956012)):
#0  0x000055c19b7fd48f in monitor_disk_info (pb=<optimized out>, e=0x7f860407c5c0, entryAfter=<optimized out>, returncode=0x7f8605bf730c, returntext=<optimized out>, arg=<optimized out>) at /usr/include/bits/stdio2.h:67
        i = <optimized out>
        rc = 0
        dirs = 0x7f8538a14680
        buf = "partition=\"/var/log/dirsrv\" size=\"32201768960\" used=\"6259421184\" available=\"25942347776\" use%=\"19\"\000\247\205\177\000\000\364\372\017&\206\177\000\000\240:\024\247\205\177\000\000\003\000\000\000\003", '\000' <repeats 11 times>, "\200:\016+\206\177\000\000\000\b", '\000' <repeats 14 times>, "@4\024\247\205\177\000\000\033\000\000\000\033", '\000' <repeats 20 times>, "\b\000\000\000\000\000\000"...
        val = {bv_len = 98, bv_val = 0x7f8605bf5220 "partition=\"/var/log/dirsrv\" size=\"32201768960\" used=\"6259421184\" available=\"25942347776\" use%=\"19\""}
        vals = {0x7f8605bf5200, 0x0}
        total_space = 0
        avail_space = 0
        used_space = 0

So there a divide by zero because some odd partitions are showing up from:   disk_mon_get_dirs(&dirs);

(gdb) p i
$1 = <optimized out>

(gdb) p dirs[0]
$4 = 0x7f860400a250 "/var"
(gdb) p dirs[1]
$5 = 0x7f86040491c0 "/etc/dirsrv"
(gdb) p dirs[2]
$6 = 0x7f86040491b0 "/var/log/dirsrv"
(gdb) p dirs[3]
$7 = 0x7f860400a278 "fs"
(gdb) p dirs[4]
$8 = 0x7f86040eb800 "/sys/fs/cgroup/rdma"
(gdb) p dirs[5]
$9 = 0x7f86040491d0 "/dev/hugepages"
(gdb) p dirs[6]
$10 = 0x0

==> df command from sosreport ( this explains the crash)

cgroup                                         0       0         0    - /sys/fs/cgroup/rdma
hugetlbfs                                      0       0         0    - /dev/hugepages

```

**Comment by mreynolds389** [comment]
duplicate
