### ISSUE TITLE
Console fails to load schema if there are additional parentheses

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4415]
Steps to Reproduce:
1. Stop the RHDS instance
2. Add a schema line containing parentheses in the X-ORIGIN information.
For instance:

attributetypes: ( 2.16.840.1.113730.3.1.604 NAME 'testName' DESC 'Sun ONE defined attribute type' EQUALITY 2.5.13.2 SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE NO-USER-MODIFICATION USAGE directoryOperation X-ORIGIN ( 'Sun Java(TM)' 'user defined' ) )

3. Start the instance
4. Click on the Schema tab in the Console. Tables are empty.
    4-1.  Or use dsconf -j INST schema list
5. Things work fine if 'Sun Java(TM)' is changed to 'Sun Java'

Actual results:
Console doesn't load schema data.

Expected results:
Schema data should be loaded.

Additional info:
# dsconf --verbose -j ldapi://%2fvar%2frun%2fslapd-<INSTANCE>.socket schema list
DEBUG: The 389 Directory Server Configuration Tool
...
DEBUG: cn=schema get_attr_vals('objectClasses')
DEBUG: cn=schema get_attr_vals('attributeTypes')
DEBUG: list index out of range
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 134, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.6/site-packages/lib389/cli_conf/schema.py", line 32, in list_all
    attributetype_elems = schema.get_attributetypes(json=json)
  File "/usr/lib/python3.6/site-packages/lib389/schema.py", line 390, in get_attributetypes
    return self._get_schema_objects(AttributeType, json=json)
  File "/usr/lib/python3.6/site-packages/lib389/schema.py", line 149, in _get_schema_objects
    obj_i['x_origin'] = vals[0]
IndexError: list index out of range
{"desc": "list index out of range"}#
#

**Comment by mreynolds389** [comment]
c4b1be456..264f173ae  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
f3317020b..c5d7865a6  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
4a8de7537..53d37df7f  389-ds-base-1.4.2 -> 389-ds-base-1.4.2

**Comment by mreynolds389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1892453
