### ISSUE TITLE
PKI cloning fails on F33

### ISSUE THREAD

**Issue by edewata** [389ds/389-ds-base#4436]
**Issue Description**

As part of cloning process, PKI normally adds `cn=changelog5,cn=config` into DS. This operation works fine on F31 and F32, but fails on F33.

Here's the code:
https://github.com/dogtagpki/pki/blob/master/base/server/src/com/netscape/cms/servlet/csadmin/LDAPConfigurator.java#L706-L720

Here's the log:
https://github.com/edewata/pki/runs/1393575646#step:21:522

```
SEVERE: Unable to add cn=changelog5,cn=config: error result
netscape.ldap.LDAPException: error result (53); Changelog configuration is part of the backend configuration; LDAP server is unwilling to perform
	at netscape.ldap.LDAPConnection.checkMsg(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at com.netscape.cms.servlet.csadmin.LDAPConfigurator.createChangeLog(LDAPConfigurator.java:720)
	at com.netscape.cms.servlet.csadmin.LDAPConfigurator.setupReplicationAgreement(LDAPConfigurator.java:873)
	at org.dogtagpki.server.cli.SubsystemDBInitCLI.setupReplicationAgreements(SubsystemDBInitCLI.java:329)
	at org.dogtagpki.server.cli.SubsystemDBInitCLI.setupReplication(SubsystemDBInitCLI.java:264)
	at org.dogtagpki.server.cli.SubsystemDBInitCLI.execute(SubsystemDBInitCLI.java:171)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:57)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.server.cli.PKIServerCLI.execute(PKIServerCLI.java:92)
	at org.dogtagpki.server.cli.PKIServerCLI.main(PKIServerCLI.java:122)
```

**Package Version and Platform:**
 - Platform: Fedora 33
 - Package and version: 389-ds-base-1.4.4.8-1.fc33.x86_64

**Steps to Reproduce**
PKI cloning procedure is documented here:
https://github.com/dogtagpki/pki/blob/master/docs/installation/ca/Installing_CA_Clone.md

**Expected results**
Is this a bug or is this a new behavior since F33? If it's a new behavior, please provide the documentation. Does PKI need to maintain different code for F31, F32, and F33, or is there a way to use the same code for all platforms?

**Additional context**
Depending on how IPA uses PKI, this issue might affect IPA cloning as well.

**Comment by mreynolds389** [comment]
In F33 the changelog was moved, and it is now automatically created when you enable replication.  If PKI sets any kind of changelog trimming it must now be done on:

    cn=changelog,cn=YOUR_BACKEND_NAME,cn=ldbm database,cn=plugins,cn=config

Or for example:

    cn=changelog,cn=userroot,cn=ldbm database,cn=plugins,cn=config

See for other details:

https://www.port389.org/docs/389ds/design/integrate-changelog-database-and-backend-database.html

I do apologize, this went through IPA testing, but not through PKI testing...

**Comment by edewata** [comment]
Just a note, this issue was addressed in PKI:
https://github.com/dogtagpki/pki/pull/3380

Thanks!
