### ISSUE TITLE
test_slapd with ASAN reports memory leak

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4479]
**Issue Description**
This is a follow up to https://github.com/389ds/389-ds-base/pull/4465#pullrequestreview-540941114
Looks like it's not our memory leak, so adding this just for reference, in case someone else hits this.

On Fedora 33 build with ASAN started to report memory leaks in `test_slapd`. RPM build with ASAN fails because of this.
Same code on Fedora 32 doesn't produce memory leak.
I tracked down the problem to nss and p11-kit packages.  

**Package Version and Platform:**
Fedora 33
p11-kit-0.23.21-2.fc33.x86_64
nss-3.58.0-3.fc33.x86_64

**Steps to Reproduce**
```
$ ./autogen.sh && ./configure --enable-asan --enable-debug --enable-cmocka && make check
$ ASAN_OPTIONS=fast_unwind_on_malloc=0 ./test_slapd
=================================================================
==237383==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8194 byte(s) in 2 object(s) allocated from:
    #0 0x7fc362ddb667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x7fc362d6f900  (/lib64/libasan.so.6+0x44900)
    #2 0x7fc35e3c57dd  (<unknown module>)
    #3 0x7fc35e3ca338  (<unknown module>)
    #4 0x7fc35e3ce149  (<unknown module>)
    #5 0x7fc3625272ca in secmod_LoadPKCS11Module /usr/src/debug/nss-3.58.0-3.fc33.x86_64/nss/lib/pk11wrap/pk11load.c:518
    #6 0x7fc36253411c in SECMOD_LoadModule /usr/src/debug/nss-3.58.0-3.fc33.x86_64/nss/lib/pk11wrap/pk11pars.c:1840
    #7 0x7fc362534257 in SECMOD_LoadModule /usr/src/debug/nss-3.58.0-3.fc33.x86_64/nss/lib/pk11wrap/pk11pars.c:1876
    #8 0x7fc3624fd830 in nss_Init /usr/src/debug/nss-3.58.0-3.fc33.x86_64/nss/lib/nss/nssinit.c:712
    #9 0x7fc3624fdd21 in NSS_Initialize /usr/src/debug/nss-3.58.0-3.fc33.x86_64/nss/lib/nss/nssinit.c:889
    #10 0x405fef in test_plugin_pwdstorage_nss_setup test/plugins/pwdstorage/pbkdf2.c:17
    #11 0x7fc362d23e42  (/lib64/libcmocka.so.0+0x5e42)
    #12 0x7fc362d24434 in _cmocka_run_group_tests (/lib64/libcmocka.so.0+0x6434)
    #13 0x405f0e in run_plugin_tests test/plugins/test.c:30
    #14 0x402558 in main test/main.c:16
    #15 0x7fc36228e041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #16 0x40247d in _start (/workspace/ds/.libs/lt-test_slapd+0x40247d)

SUMMARY: AddressSanitizer: 8194 byte(s) leaked in 2 allocation(s).
```

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1905581

**Comment by vashirov** [comment]
This leak is fixed in F33 with https://bodhi.fedoraproject.org/updates/FEDORA-2021-b848e92d08

**Comment by vashirov** [comment]
Update is in stable repos, closing.
