### ISSUE TITLE
Demoting a supplier to a consumer crashes the server

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4731]
**Issue Description**
When demoting a supplier to a consumer, the server calls cl5CleanRUV on a replica that has no more changelog. cl5CleanRuv dereference the changelog that is NULL and crash

**Package Version and Platform:**
It happens F34/rawhide

**Steps to Reproduce**
Running the following command crash the server
dsconf -D "cn=Directory Manager" ldap://server.example.com replication demote --suffix="dc=example,dc=com" --newrole="consumer"

**Expected results**
It should not crash

**Comment by tbordaz** [comment]
The crash occurs when the replica is modified to a consumer role:
update MOD_REPL
nsDS5ReplicaType: 2
nsDS5Flags: 0
nsDS5ReplicaId: 65535

<pre>
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[0]
$19 = {mod_op = 130, mod_type = 0x7fc4a5006e40 "nsDS5ReplicaType", mod_vals = {modv_strvals = 0x7fc4a50355d0,
    modv_bvals = 0x7fc4a50355d0}}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[0]->mod_vals.modv_bvals[0]
$25 = {bv_len = 1, bv_val = 0x7fc4a5032240 "2"}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[1]
$26 = {mod_op = 130, mod_type = 0x7fc4a5035650 "nsDS5Flags", mod_vals = {modv_strvals = 0x7fc4a5035660, modv_bvals = 0x7fc4a5035660}}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[1]->mod_vals.modv_bvals[0]
$27 = {bv_len = 1, bv_val = 0x7fc4a5032248 "0"}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[2]
$28 = {mod_op = 130, mod_type = 0x7fc4a5035680 "nsDS5ReplicaId", mod_vals = {modv_strvals = 0x7fc4a5035690, modv_bvals = 0x7fc4a5035690}}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[1]->mod_vals.modv_bvals[0]
$29 = {bv_len = 1, bv_val = 0x7fc4a5032248 "0"}
(gdb) print *pb->pb_op->o_params.p.p_modify.modify_mods[2]->mod_vals.modv_bvals[0]
$30 = {bv_len = 5, bv_val = 0x7fc4a5032250 "65535"}
</pre>

replica_config_change_type_and_id calls cl5CleanRUV with a replica having no CL

<pre>
(gdb) where
#0  0x00007fc4a66657d9 in cl5CleanRUV (rid=<optimized out>, replica=<optimized out>) at ldap/servers/plugins/replication/cl5_api.c:4398
#1  0x00007fc4a6687497 in replica_config_change_type_and_id
    (apply_mods=1, returntext=0x7fc4911a9700 "", new_id=<optimized out>, new_type=<optimized out>, r=0x7fc4a9e30600)
    at ldap/servers/plugins/replication/repl5_replica_config.c:1030
#2  replica_config_modify
    (pb=0x7fc4a4e9d7e0, entryBefore=<optimized out>, e=<optimized out>, returncode=0x7fc4911a96c4, returntext=<optimized out>, arg=<optimized out>) at ldap/servers/plugins/replication/repl5_replica_config.c:637
#3  0x00007fc4ab7e32b2 in dse_call_callback.isra.0
    (pb=0x7fc4a4e9d7e0, operation=8, flags=1, entryBefore=0x7fc4a5040c00, entryAfter=0x7fc4a5040e40, returncode=0x7fc4911a96c4, returntext=0x7fc4911a9700 "", pdse=<optimized out>, pdse=<optimized out>) at ldap/servers/slapd/dse.c:2677
#4  0x00007fc4ab75aa80 in dse_modify (pb=0x7fc4a4e9d7e0) at ldap/servers/slapd/dse.c:1872
#5  0x00007fc4ab78a9f6 in op_shared_modify (pb=pb@entry=0x7fc4a4e9d7e0, pw_change=pw_change@entry=0, old_pw=0x0)
    at ldap/servers/slapd/modify.c:1022
#6  0x00007fc4ab78b65d in do_modify (pb=pb@entry=0x7fc4a4e9d7e0) at ldap/servers/slapd/modify.c:377
#7  0x000055b712355094 in connection_dispatch_operation (pb=0x7fc4a4e9d7e0, op=0x7fc4a6b5ec00, conn=0x7fc4a575cb88)
    at ldap/servers/slapd/connection.c:635
#8  connection_threadmain () at ldap/servers/slapd/connection.c:1777
#9  0x00007fc4ab2604a4 in _pt_root () at /lib64/libnspr4.so
#10 0x00007fc4ab1f3299 in start_thread () at /lib64/libpthread.so.0
#11 0x00007fc4ab58d6a3 in clone () at /lib64/libc.so.6

(gdb) frame 1
#1  0x00007fc4a6687497 in replica_config_change_type_and_id (apply_mods=1, returntext=0x7fc4911a9700 "", new_id=<optimized out>,
    new_type=<optimized out>, r=0x7fc4a9e30600) at ldap/servers/plugins/replication/repl5_replica_config.c:1030
1030                    cl5CleanRUV(oldrid, r);
(gdb) print r->cldb
$35 = (cldb_Handle *) 0x0
(gdb) down
#0  0x00007fc4a66657d9 in cl5CleanRUV (rid=<optimized out>, replica=<optimized out>) at ldap/servers/plugins/replication/cl5_api.c:4398
4398        ruv_delete_replica(cldb->purgeRUV, rid);
(gdb) list
4393     */
4394    void
4395    cl5CleanRUV(ReplicaId rid, Replica *replica)
4396    {
4397        cldb_Handle *cldb = replica_get_cl_info(replica);
4398        ruv_delete_replica(cldb->purgeRUV, rid);
4399        ruv_delete_replica(cldb->maxRUV, rid);
4400    }

</pre>

**Comment by tbordaz** [comment]
The problem is likely introduced by backend redesign [phase_2](https://github.com/389ds/389-ds-base/commit/0f1ab5f0531eca6af07aeda59bf4c8f97f59357f#diff-ebae981ee774d63fc4ae2f2ff1912c2c1e2840fe47180a2e34bfd98bd0181ce2R4531)

So it applies only on master branch

**Comment by tbordaz** [comment]
BZ Rhel next, 9.1
