### ISSUE TITLE
Failures in dynamic_plugins test suite

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4768]
**Issue Description**
After https://github.com/389ds/389-ds-base/issues/4656 dynamic plugins test suite started to fail:
```
FAILED dirsrvtests/tests/suites/dynamic_plugins/dynamic_plugins_test.py::test_acceptance - ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't cont...
FAILED dirsrvtests/tests/suites/dynamic_plugins/dynamic_plugins_test.py::test_memory_corruption - ldap.SERVER_DOWN: {'result': -1, 'desc': "Can...
FAILED dirsrvtests/tests/suites/dynamic_plugins/dynamic_plugins_test.py::test_stress - ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact ...
```

Server crashes with SIGSEGV:
```
(gdb) bt
#0  0x00007f3a3b05e30e in slapi_counter_add (addvalue=1, counter=0x70616c73736e0a65) at ldap/servers/slapd/slapi_counter.c:130
#1  slapi_counter_add (counter=0x70616c73736e0a65, addvalue=1) at ldap/servers/slapd/slapi_counter.c:122
#2  0x00007f3a3b08998c in dse_call_callback.isra.0
    (pb=0x7f3a13bff000, operation=16, flags=1, entryBefore=0x7f3a13c1f480, entryAfter=0x0, returncode=0x7f3a197fb728, returntext=0x7f3a197fb790 "", pdse=<optimized out>, pdse=<optimized out>) at ldap/servers/slapd/dse.c:2666
#3  0x00007f3a3affe664 in dse_add (pb=0x7f3a13bff000) at ldap/servers/slapd/dse.c:2375
#4  0x00007f3a3afea947 in op_shared_add (pb=pb@entry=0x7f3a13bff000) at ldap/servers/slapd/add.c:758
#5  0x00007f3a3afeb7d3 in do_add (pb=pb@entry=0x7f3a13bff000) at ldap/servers/slapd/add.c:236
#6  0x0000559e5eb8d0ce in connection_dispatch_operation (pb=0x7f3a13bff000, op=0x7f3a363f6800, conn=0x7f3a1d480d48)
    at ldap/servers/slapd/connection.c:620
#7  connection_threadmain () at ldap/servers/slapd/connection.c:1777
#8  0x00007f3a3ab034a4 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f3a3aa96299 in start_thread (arg=0x7f3a197fe640) at pthread_create.c:481
#10 0x00007f3a3ae31353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 40edb3cd914a7dd795f1e8a461400ecb7740d387

**Steps to Reproduce**
Run `dirsrvtests/tests/suites/dynamic_plugins/`

**Expected results**
Server should not crash and tests should pass.

**Comment by mreynolds389** [comment]
Fixed in https://github.com/389ds/389-ds-base/pull/4804
