### ISSUE TITLE
389-ds-base fails to compile in Fedora 35 due to Rust compiler changes

### ISSUE THREAD

**Issue by abbra** [389ds/389-ds-base#5061]
According to Koschei service, https://koschei.fedoraproject.org/package/389-ds-base?collection=f35, 389-ds-base started to fail builds in Fedora 35 yesterday. Looking at x86_64 logs, I can see this:

```
     Running `rustc --crate-name rnsslapd --edition=2018 librnsslapd/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=1ddeb212a78a71ae -C extra-filename=-1ddeb212a78a71ae --out-dir /builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps -L dependency=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps --extern libc=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps/liblibc-622b8a9bafdb0b72.rlib --extern slapd=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps/libslapd-44a1a02774b2202f.rlib`
error: unused return value of `CString::from_raw` that must be used
  --> librnsslapd/src/lib.rs:35:25
   |
35 |                         CString::from_raw(raw);
   |                         ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> librnsslapd/src/lib.rs:1:9
   |
1  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_must_use)]` implied by `#[deny(warnings)]`
   = note: call `drop(from_raw(ptr))` if you intend to drop the `CString`
error: could not compile `librnsslapd` due to previous error
Caused by:
  process didn't exit successfully: `rustc --crate-name rnsslapd --edition=2018 librnsslapd/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=1ddeb212a78a71ae -C extra-filename=-1ddeb212a78a71ae --out-dir /builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps -L dependency=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps --extern libc=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps/liblibc-622b8a9bafdb0b72.rlib --extern slapd=/builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/deps/libslapd-44a1a02774b2202f.rlib` (exit status: 1)
make: *** [Makefile:12738: /builddir/build/BUILD/389-ds-base-2.0.11/rs/rnsslapd/release/librnsslapd.a] Error 101
error: Bad exit status from /var/tmp/rpm-tmp.BTFdty (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.BTFdty (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/mockbuild/util.py", line 600, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/389-ds-base.spec
```

**Comment by Firstyear** [comment]
Already fixed.

**Comment by abbra** [comment]
For the reference, this is the same as https://github.com/389ds/389-ds-base/issues/5043
