### ISSUE TITLE
lib389: backend add_index fails if matching_rules is not defined

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5080]
**Issue Description**
add_index method of 'Backend' class, defines
<pre>
    def add_index(self, attr_name, types, matching_rules=[], reindex=False):
...
        if matching_rules is not None:
            mrs = []
            for mr in matching_rules:
                mrs.append(mr)
            props['nsMatchingRule'] = mrs
</pre>

If matching_rules is not provided it is an empty list. It should not be tested None or its default value should be None

**Package Version and Platform:**
since 1.4.3

**Steps to Reproduce**
Initially reported with 'openldap_to_ds' command. A test creating an index without providing matching rules should report 
<pre>
ldap.PROTOCOL_ERROR: {'desc': 'Protocol error'}
ERROR: Error: Protocol error
</pre>

**Expected results**
add_index should not fail if the matching rule is not defined.

**Comment by jirib** [comment]
I reporeted this with `openldap_to_ds` initially. I'm not sure if this is relevant but after relaxing the above condition, the migration failed with:

```
DEBUG: _gen_selector filter = (&(&(objectclass=nsBackendInstance))(|(cn=dc=dla-e
xample,dc=com)(nsslapd-suffix=dc=dla-example,dc=com)(nsslapd-directory=dc=dla-marb
ach,dc=com)))
DEBUG: _gen_selector filter = (&(&(objectclass=nsIndex))(|(cn=displayName)))
DEBUG: Checking "None" under cn=index,cn=userroot,cn=ldbm database,cn=plugins,cn
=config : {'cn': 'displayName', 'nsSystemIndex': 'False', 'nsIndexType': 'pres,e
q,sub'}
DEBUG: Using first property cn: displayName as rdn
DEBUG: Validated dn cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plug
ins,cn=config
DEBUG: Creating cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plugins,
cn=config
DEBUG: updating dn: cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plug
ins,cn=config
DEBUG: updated dn: cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plugi
ns,cn=config with {'objectclass': [b'top', b'nsIndex']}
DEBUG: updating dn: cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plug
ins,cn=config
DEBUG: updated dn: cn=displayName,cn=index,cn=userroot,cn=ldbm database,cn=plugi
ns,cn=config with {'cn': [b'displayName'], 'nsSystemIndex': [b'False'], 'nsIndex
Type': [b'pres,eq,sub']}
DEBUG: {'desc': 'Operations error', 'info': 'Error: from DSE add: line 0: unknow
n index type "pres,eq,sub" (ignored) in entry (cn=displayName,cn=index,cn=userro
ot,cn=ldbm database,cn=plugins,cn=config), valid index types are "pres", "eq", "
approx", or "sub"\n'}
Traceback (most recent call last):
  File "/usr/sbin/openldap_to_ds", line 250, in <module>
    result = do_migration(inst, log, args, skip_overlays)
  File "/usr/sbin/openldap_to_ds", line 209, in do_migration
    migration.execute_plan(log)
  File "/usr/lib/python3.6/site-packages/lib389/migrate/plan.py", line 656, in e
xecute_plan
    item.apply(self.inst)
  File "/usr/lib/python3.6/site-packages/lib389/migrate/plan.py", line 77, in ap
ply
    be.add_index(self.attr, self.type)
  File "/usr/lib/python3.6/site-packages/lib389/backend.py", line 740, in add_in
dex
    new_index.create(properties=props, basedn="cn=index," + self._dn)
  File "/usr/lib/python3.6/site-packages/lib389/_mapped_object.py", line 985, in
 create
    return self._create(rdn, properties, basedn, ensure=False)
  File "/usr/lib/python3.6/site-packages/lib389/_mapped_object.py", line 960, in
 _create
    self._instance.add_ext_s(e, serverctrls=self._server_controls, clientctrls=s
elf._client_controls, escapehatch='i am sure')
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 170, in inner

    return f(ent.dn, ent.toTupleList(), *args[2:])
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 414, in add
_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,time
out=self.timeout)
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 174, in inner

    return f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 749, in res
ult3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 174, in inner

    return f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 756, in res
ult4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,ad
d_intermediates,add_extop)
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 174, in inner

    return f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 329, in _ld
ap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib64/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 313, in _ld
ap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'desc': 'Operations error', 'info': 'Error: from DSE add
: line 0: unknown index type "pres,eq,sub" (ignored) in entry (cn=displayName,cn
=index,cn=userroot,cn=ldbm database,cn=plugins,cn=config), valid index types are
 "pres", "eq", "approx", or "sub"\n'}
ERROR: Error: Operations error - Error: from DSE add: line 0: unknown index type
 "pres,eq,sub" (ignored) in entry (cn=displayName,cn=index,cn=userroot,cn=ldbm d
atabase,cn=plugins,cn=config), valid index types are "pres", "eq", "approx", or
"sub"
```
If this is related then I'm available on the project's IRC channel to provide more details if needed.

**Comment by tbordaz** [comment]
@jirib it looks to me a different issue (using the same openldap_to_ds tool) that the one reported in that ticket. The original issue leads to 'protocol error' because 'nsMatchingRule' gets '[]'.

The new error is a OPERATIONS_ERROR, because of a MOD 'nsIndexType: pres,eq,sub' rather than
<pre>
nsIndexType: pres
nsIndexType: eq
nsIndexType: sub
</pre>
IMHO the RC is rather in openldap_to_ds than in lib389

**Comment by Firstyear** [comment]
@tbordaz I think you're right, I'll have a look at this.
