### ISSUE TITLE
Container may fail with bare uid/gid

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5102]
```
ldapkdc% id
uid=1400 gid=1400 groups=1400
ldapkdc% dscontainer -r
INFO: The 389 Directory Server Container Bootstrap
INFO: Inspired by works of: ITS, The University of Adelaide
INFO: 389 Directory Server Version: 2.1.0.20220112git6f84b0b61
INFO: Initialising 389-ds-container due to empty volume ...
Traceback (most recent call last):
  File "/home/william/development/389ds/ds/src/lib389/cli/dscontainer", line 443, in <module>
    begin_magic()
  File "/home/william/development/389ds/ds/src/lib389/cli/dscontainer", line 230, in begin_magic
    user_name = pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1400'
```

This should suceed.

**Comment by Firstyear** [comment]
The fix will be to build the container with https://github.com/kanidm/nss_synth in the base, I'll close this once complete.
