### ISSUE TITLE
ns-slapd crash in CI test plugins test_dna_interval_with_different_values

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5104]
**Issue Description**
ns-slapd crash in CI test plugins test_dna_interval_with_different_values
because the operation modifiers is corrupted when trying to log the operation
 According to the operation we are handling modify operation on uid=interval3,ou=People,dc=example,dc=com replace uidNumber: -1
Crash is systematic both with bdb and mdb ( maybe a Bug in normalize_mods2bvals ? )

**Package Version and Platform:**
 - Platform: fedora 35:
 - Package and version:  I reproduced it with [Issue 4939 PR](https://github.com/389ds/389-ds-base/pull/5071) that said it probably occurs on master too

**Steps to Reproduce**
Set up 1minuteTips VM with fedora 35
Once test is complete log with ssh and run:

```
pip install -U setuptools
pip install -U pytest
pip install -U slugify
sysctl -w fs.suid_dumpable=1
cd /mnt/tests/rhds/tests/upstream/ds/dirsrvtests/tests/suites/plugins
#export NSSLAPD_DB_LIB=mdb

DEBUGGING=1 py.test --log-level=debug -vvvvv $PWD -k test_dna_interval_with_different_values
coredumpctl debug
```

**Expected results**
Test should be pass and coredumpctl should not report any core file
( Currently test is PASS but a core file is reported)

**Additional context**
```
Core was generated by `/usr/sbin/ns-slapd -D /etc/dirsrv/slapd-standalone1 -i /run/dirsrv/slapd-standa'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  write_audit_file (logtype=logtype@entry=4, optype=<optimized out>, dn=dn@entry=0x7f7575f82e90 "uid=interval3,ou=People,dc=example,dc=com", change=change@entry=0x7f7575fc3600, flag=flag@entry=0, curtime=curtime@entry=1642082606, rc=1, sourcelog=8) at ldap/servers/slapd/auditlog.c:233
233             int operationtype = mods[j]->mod_op & ~LDAP_MOD_BVALUES;
[Current thread is 1 (Thread 0x7f7579352640 (LWP 323802))]
(gdb) where
#0  write_audit_file
    (logtype=logtype@entry=4, optype=<optimized out>, dn=dn@entry=0x7f7575f82e90 "uid=interval3,ou=People,dc=example,dc=com", change=change@entry=0x7f7575fc3600, flag=flag@entry=0, curtime=curtime@entry=1642082606, rc=1, sourcelog=8) at ldap/servers/slapd/auditlog.c:233
#1  0x00007f7592edab13 in write_auditfail_log_entry (pb=<optimized out>) at ldap/servers/slapd/auditlog.c:166
#2  0x00007f7592f24181 in op_shared_modify (pb=pb@entry=0x7f758d7f2540, pw_change=pw_change@entry=0, old_pw=0x0) at ldap/servers/slapd/modify.c:1047
#3  0x00007f7592f24b8d in do_modify (pb=pb@entry=0x7f758d7f2540) at ldap/servers/slapd/modify.c:377
#4  0x000055b4e5349ce9 in connection_dispatch_operation (pb=0x7f758d7f2540, op=<optimized out>, conn=<optimized out>) at ldap/servers/slapd/connection.c:648
#5  connection_threadmain (arg=<optimized out>) at ldap/servers/slapd/connection.c:1800
#6  0x00007f75929a8524 in _pt_root (arg=0x7f758edb8140) at ../../../../nspr/pr/src/pthreads/ptthread.c:201
#7  0x00007f7592c69a87 in start_thread (arg=<optimized out>) at pthread_create.c:435
#8  0x00007f7592cee640 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) up 2
#2  0x00007f7592f24181 in op_shared_modify (pb=pb@entry=0x7f758d7f2540, pw_change=pw_change@entry=0, old_pw=0x0) at ldap/servers/slapd/modify.c:1047
1047                        write_auditfail_log_entry(pb); /* Record the operation in the audit log */
(gdb) p *pb->pb_op->o_params.p
Attempt to take contents of a non-pointer value.
(gdb) p pb->pb_op->o_params.p
$1 = {p_add = {target_entry = 0x7f7575fc3600, parentuniqueid = 0x0}, p_bind = {bind_method = 140142467364352, bind_creds = 0x0, bind_saslmechanism = 0x0, bind_ret_saslcreds = 0x0}, p_compare = {compare_ava = {
      ava_type = 0x7f7575fc3600 "\202", ava_value = {bv_len = 0, bv_val = 0x0}, ava_private = 0x0}}, p_modify = {modify_mods = 0x7f7575fc3600}, p_modrdn = {modrdn_newrdn = 0x7f7575fc3600 "\202",
    modrdn_deloldrdn = 0, modrdn_newsuperior_address = {udn = 0x0, uniqueid = 0x0, sdn = 0x0}, modrdn_mods = 0x0}, p_search = {search_scope = 1979463168, search_deref = 32629, search_sizelimit = 0,
    search_timelimit = 0, search_filter = 0x0, search_strfilter = 0x0, search_attrs = 0x0, search_attrsonly = 0, search_is_and = 0, search_gerattrs = 0x0}, p_abandon = {abandon_targetmsgid = 1979463168},
  p_extended = {exop_oid = 0x7f7575fc3600 "\202", exop_value = 0x0}}
(gdb) p pb->pb_op->o_params.p.p_modify.modify_mods
$2 = (LDAPMod **) 0x7f7575fc3600
(gdb) p pb->pb_op->o_params.p.p_modify.modify_mods[0][0]
Cannot access memory at address 0x7f7500000082

```

Note: Although the test is PASS this bug may cause failure to other CI tests (because the instance is down while it is expected up)

**Comment by progier389** [comment]
FYI: Was not able to reproduce with asan on my machine

**Comment by vashirov** [comment]
I've reported a similar crash in plugins test suite https://github.com/389ds/389-ds-base/issues/5065 
I also was not able to reproduce it with ASAN.
