### ISSUE TITLE
`dsconf instance backend suffix set` doesn't accept backend name

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5122]
**Issue Description**
Help shows that backend name is acceptable parameter:
```
# dsconf instance1  backend suffix set --help
usage: dsconf instance backend suffix set [-h] [--enable-readonly] [--disable-readonly] [--require-index] [--ignore-index]
                                          [--add-referral ADD_REFERRAL] [--del-referral DEL_REFERRAL] [--enable] [--disable]
                                          [--cache-size CACHE_SIZE] [--cache-memsize CACHE_MEMSIZE] [--dncache-memsize DNCACHE_MEMSIZE]
                                          [--state STATE]
                                          be_name

positional arguments:
  be_name               The backend name or suffix
...
```

But when I pass it, I get empty error:
```
# dsconf instance1  backend suffix list 
dc=example,dc=com (userroot)
ou=data_on_instance1,dc=example,dc=com (data_on_1)

# dsconf -v instance1 backend suffix set --del-referral="ldap://localhost:38902/ou=people,dc=example,dc=com" data_on_1
...
DEBUG: list filter = (&(objectclass=nsBackendInstance))
DEBUG: cn=data_on_1,cn=ldbm database,cn=plugins,cn=config getVal('nsslapd-suffix')
DEBUG: cn=data_on_1,cn=ldbm database,cn=plugins,cn=config getVal('cn')
DEBUG:
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 138, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.10/site-packages/lib389/cli_conf/backend.py", line 474, in backend_set
    be = _get_backend(inst, args.be_name)
  File "/usr/lib/python3.10/site-packages/lib389/cli_conf/backend.py", line 110, in _get_backend
    if str2dn(be_suffix) == str2dn(name.lower()) or cn == name.lower():
  File "/usr/lib64/python3.10/site-packages/ldap/dn.py", line 52, in str2dn
    return ldap.functions._ldap_function_call(None,_ldap.str2dn,dn,flags)
  File "/usr/lib64/python3.10/site-packages/ldap/functions.py", line 55, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.DECODING_ERROR
ERROR: Error:

```
**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.0.12-1.fc35.x86_64

**Comment by progier389** [comment]
It is a easy to fix issue that may have a painful impact as you can waste a lot of time before understanding what happens (because the online help tells to use the bename) as I experimented today when trying to add an index !

**Comment by mreynolds389** [comment]
Can you please cherry pick this down to 1.4.3?  Thanks!

**Comment by progier389** [comment]
37995ff4c..b527b3454 master
f50637aeb..f969fd936  389-ds-base-2.0 -> 389-ds-base-2.0
324bf991c..d84894150  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
2e4625fc5..7a9c8e3ad  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
