### ISSUE TITLE
`dscontainer` fails to create an instance

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5124]
**Issue Description**
5f05bc7af82edf4690c0dce0ceaab8ac328b70a6 changed `pid_file` location in `defaults.inf`:

```diff
-pid_file = @localstatedir@/run/dirsrv/slapd-{instance_name}.pid
+pid_file = @localrundir@/slapd-{instance_name}.pid
```
In rpm builds this resulted in the following change:
```diff
-pid_file = /var/run/dirsrv/slapd-{instance_name}.pid
+pid_file = /run/slapd-{instance_name}.pid
```

In `dscontainer` we set it to a different location:
https://github.com/389ds/389-ds-base/blob/5f05bc7af82edf4690c0dce0ceaab8ac328b70a6/src/lib389/lib389/paths.py#L153-L156
But this doesn't help when instance doesn't exist, so it fails on a first start:
```
DEBUG: pid file /run/slapd-localhost.pid -> None
DEBUG: No pidfile found for localhost
DEBUG: systemd status -> False
DEBUG: DEBUG: starting with ['/usr/sbin/ns-slapd', '-D', '/etc/dirsrv/slapd-localhost', '-i', '/run/slapd-localhost.pid']
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
INFO: selinux is disabled, will not relabel ports or files.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.10/site-packages/lib389/instance/setup.py", line 921, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.10/site-packages/lib389/__init__.py", line 1124, in start
    raise ValueError('Failed to start DS')
ValueError: Failed to start DS
```

When an instance is created, it is started for the first time with PID file pointing to `/run/slapd-{instance_name}.pid`:
https://github.com/389ds/389-ds-base/blob/e0db9ec15756cfaacd57a0ccbd243ee8f7a2f55b/src/lib389/lib389/__init__.py#L1130-L1135

On a non-containerized systems, when we run `dscreate`, it runs as root, so PID file can written in `/run/` .
And when instance is created, it is started by systemd, and it actually uses a different hardcoded path:
https://github.com/389ds/389-ds-base/blob/e0db9ec15756cfaacd57a0ccbd243ee8f7a2f55b/wrappers/systemd.template.service.in#L15-L17

```
$ grep -i pid /usr/lib/systemd/system/dirsrv@.service 
PIDFile=/run/dirsrv/slapd-%i.pid
ExecStart=/usr/sbin/ns-slapd -D /etc/dirsrv/slapd-%i -i /run/dirsrv/slapd-%i.pid
```

But in `dscontainer` instance creation happens as `dirsrv` user and `/run` is not writeable for this user.

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.0.11+, starting from 5f05bc7af82edf4690c0dce0ceaab8ac328b70a6

**Comment by vashirov** [comment]
0130544ea..de212e22b  389-ds-base-2.0 -> 389-ds-base-2.0

**Comment by vashirov** [comment]
669de11a0..a82c2a595  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
