### ISSUE TITLE
v2.0.14 not support alpine 3.14

### ISSUE THREAD

**Issue by paddy235** [389ds/389-ds-base#5207]
**Issue Description**
from 
https://github.com/4teamwork/389ds-docker/blob/master/Dockerfile

**Package Version and Platform:**
 - Platform: alpine 3.14
 - Package and version: https://github.com/389ds/389-ds-base/commit/eccfa2af9dd6f07a0354ea0698a5582cfb17c367
 - Browser 

**Steps to Reproduce**
1. Go to 'https://github.com/4teamwork/389ds-docker'
2. git clone https://github.com/4teamwork/389ds-docker
3. docker build 

```
DEBUG: PASSED: instance checking
DEBUG: INFO: temp root password set to Oae766.hyb47GDK453Vl5QJZyrb1jLRpgG1lCjAb03ISTycTppWLpXB498ChV4f.F
DEBUG: PASSED: root user checking
DEBUG: PASSED: network avaliability checking
DEBUG: READY: Beginning installation for localhost...
DEBUG: ACTION: Creating dse.ldif
Traceback (most recent call last):
  File "/usr/libexec/dirsrv/dscontainer", line 443, in <module>
    begin_magic()
  File "/usr/libexec/dirsrv/dscontainer", line 266, in begin_magic
    if not sds.create_from_args(g2b.collect(), s2b.collect()):
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 737, in _install_ds
    container_result = subprocess.run(["systemd-detect-virt", "-c"], stdout=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemd-detect-virt'
INFO: The 389 Directory Server Container Bootstrap
INFO: Inspired by works of: ITS, The University of Adelaide
INFO: 389 Directory Server Version: 2.0.14
INFO: Initialising 389-ds-container due to empty volume ...
DEBUG: Running setup with verbose
DEBUG: START: Starting installation ...
DEBUG: READY: Preparing installation for localhost...
INFO: Validate installation settings ...
DEBUG: PASSED: using config settings 999999999
DEBUG: PASSED: user / group checking
DEBUG: PASSED: prefix checking
DEBUG: list instance not found in /etc/dirsrv/slapd-localhost/dse.ldif: localhost



```

**Expected results**

**Screenshots**

**Additional context**

**Comment by Firstyear** [comment]
This has already been resolved in https://github.com/389ds/389-ds-base/commit/d04ffd4b65c4f3aef7b363cff2be139df1b780c2 and will be resolved in the next 2.0 release :)
