### ISSUE TITLE
dsidm user get_dn fails with search_ext() argument 1 must be str, not function

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5373]
**Issue Description**

    # dsidm -v localhost -b dc=example,dc=com  user get_dn

...
DEBUG: _gen_dn filter = (&(objectclass=nsPerson)(objectclass=nsAccount)(objectclass=nsOrgPerson)(objectclass=posixAccount))
DEBUG: _gen_dn dn = <function get_dn.<locals>.<lambda> at 0x7f91dd05cdc0>
DEBUG: search_ext() argument 1 must be str, not function
Traceback (most recent call last):
  File "/usr/sbin/dsidm", line 141, in <module>
    result = args.func(inst, dsrc_inst['basedn'], log, args)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/cli_idm/user.py", line 38, in get_dn
    _generic_get_dn(inst, basedn, log.getChild('_generic_get_dn'), MANY, dn, args)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/cli_idm/__init__.py", line 101, in _generic_get_dn
    o = mc.get(dn=dn)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/_mapped_object.py", line 1185, in get
    results = self._get_dn(dn)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/_mapped_object.py", line 1203, in _get_dn
    return _search_ext_s(self._instance,
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/_mapped_object.py", line 92, in _search_ext_s
    return _ldap_op_s(inst, inst.search_ext_s, 'search_ext_s', *args, **kwargs)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/_mapped_object.py", line 74, in _ldap_op_s
    return f(*args, **kwargs)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/__init__.py", line 176, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 863, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/__init__.py", line 176, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 853, in search_ext
    return self._ldap_call(
  File "/home/mareynol/source/ds389/389-ds-base/src/lib389/lib389/__init__.py", line 176, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
TypeError: search_ext() argument 1 must be str, not function
ERROR: Error: search_ext() argument 1 must be str, not function

**Comment by mreynolds389** [comment]
1f0107811..3576e79e8  389-ds-base-2.1 -> 389-ds-base-2.1
e2f735446..c0c099622  389-ds-base-2.0 -> 389-ds-base-2.0
1a2bcefa7..01a3d566b  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by droideck** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1893667
