### ISSUE TITLE
Memory leak in filter optimizer

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5397]
**Issue Description**

Looks like we have some memory leaks caused by the filter optimizer RFE:

```
Indirect leak of 120 byte(s) in 10 object(s) allocated from:
    #0 0x7fc6a5cae377 in strdup (/lib64/libasan.so.6+0x5a377)
    #1 0x7fc6a54db0bb in slapi_ch_strdup ldap/servers/slapd/ch_malloc.c:196
    #2 0x7fc6a54ca26c in slapi_attr_syntax_normalize ldap/servers/slapd/attrsyntax.c:539
    #3 0x7fc6a5535bac in filter_normalize_ava ldap/servers/slapd/filter.c:1046
    #4 0x7fc6a5536a4f in filter_normalize_ext ldap/servers/slapd/filter.c:1144
    #5 0x7fc6a5536916 in filter_normalize_list ldap/servers/slapd/filter.c:1118
    #6 0x7fc6a5536ca0 in filter_normalize_ext ldap/servers/slapd/filter.c:1165
    #7 0x7fc6a5536916 in filter_normalize_list ldap/servers/slapd/filter.c:1118
    #8 0x7fc6a5536c64 in filter_normalize_ext ldap/servers/slapd/filter.c:1162
    #9 0x7fc6a5536d8b in slapi_filter_normalize ldap/servers/slapd/filter.c:1184
    #10 0x7fc69d54d083 in ldbm_back_search ldap/servers/slapd/back-ldbm/ldbm_search.c:959
    #11 0x7fc6a55c0eb1 in op_shared_search ldap/servers/slapd/opshared.c:821
    #12 0x7fc6a5607e6a in search_internal_callback_pb ldap/servers/slapd/plugin_internal_op.c:730
    #13 0x7fc6a5606ea7 in search_internal_pb ldap/servers/slapd/plugin_internal_op.c:594
    #14 0x7fc6a56067ba in slapi_search_internal_pb ldap/servers/slapd/plugin_internal_op.c:504
    #15 0x7fc6a56bf134 in vattr_check_thread ldap/servers/slapd/vattr.c:183
    #16 0x7fc6a4a48553 in _pt_root ../../.././nspr/pr/src/pthreads/ptthread.c:201


Indirect leak of 180 byte(s) in 10 object(s) allocated from:
    #0 0x7fc6a5d04627 in __interceptor_malloc (/lib64/libasan.so.6+0xb0627)
    #1 0x7fc6a54dab91 in slapi_ch_malloc ldap/servers/slapd/ch_malloc.c:95
    #2 0x7fc6a56b3e60 in ber_bvcpy ldap/servers/slapd/value.c:48
    #3 0x7fc6a56b3f87 in slapi_ber_bvcpy ldap/servers/slapd/value.c:65
    #4 0x7fc6a5534422 in slapi_filter_dup ldap/servers/slapd/filter.c:702
    #5 0x7fc6a5534669 in slapi_filter_dup ldap/servers/slapd/filter.c:722
    #6 0x7fc6a5534669 in slapi_filter_dup ldap/servers/slapd/filter.c:722
    #7 0x7fc69d54d038 in ldbm_back_search ldap/servers/slapd/back-ldbm/ldbm_search.c:958
    #8 0x7fc6a55c0eb1 in op_shared_search ldap/servers/slapd/opshared.c:821
    #9 0x7fc6a5607e6a in search_internal_callback_pb ldap/servers/slapd/plugin_internal_op.c:730
    #10 0x7fc6a5606ea7 in search_internal_pb ldap/servers/slapd/plugin_internal_op.c:594
    #11 0x7fc6a56067ba in slapi_search_internal_pb ldap/servers/slapd/plugin_internal_op.c:504
    #12 0x7fc6a56bf134 in vattr_check_thread ldap/servers/slapd/vattr.c:183
    #13 0x7fc6a4a48553 in _pt_root ../../.././nspr/pr/src/pthreads/ptthread.c:201


Indirect leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x7fc6a5d047f7 in __interceptor_calloc (/lib64/libasan.so.6+0xb07f7)
    #1 0x7fc6a54dafd3 in slapi_ch_calloc ldap/servers/slapd/ch_malloc.c:175
    #2 0x7fc6a55341b4 in slapi_filter_dup ldap/servers/slapd/filter.c:685
    #3 0x7fc69d54d038 in ldbm_back_search ldap/servers/slapd/back-ldbm/ldbm_search.c:958
    #4 0x7fc6a55c0eb1 in op_shared_search ldap/servers/slapd/opshared.c:821
    #5 0x4807dd in do_search ldap/servers/slapd/search.c:410
    #6 0x430824 in connection_dispatch_operation ldap/servers/slapd/connection.c:692
    #7 0x436c4f in connection_threadmain ldap/servers/slapd/connection.c:1841
    #8 0x7fc6a4a48553 in _pt_root ../../.././nspr/pr/src/pthreads/ptthread.c:201
```

**Comment by mreynolds389** [comment]
9394e7b67..2d46c8045  389-ds-base-2.1 -> 389-ds-base-2.1
3ab5ba4a5..38082145f  389-ds-base-2.0 -> 389-ds-base-2.0
fac44b69f..15a96d3ff  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
