### ISSUE TITLE
Installation in a container?

### ISSUE THREAD

**Issue by codedump** [389ds/389-ds-base#5452]
Hello,

I'm trying to install the 389 LDAP server in a podman container based on Fedora:
```
$ podman run -ti --rm -v $PWD/tmp/scratch:/scratch:z fedora:latest
$ dnf -y install 389-ds-base
$ dscreate -v from-file /scratch/ds-foo.inf
```

This is the `ds-foo.inf` I am using:

```
[general]
full_machine_name = ldap
start = False
strict_host_checking = False
systemd = False
selinux = False

[slapd]
instance_name = testds
port = 389
root_password = 12345678
self_sign_cert = False

[backend-userroot]
create_suffix_entry = False
```

And this is how it fails:
```
DEBUG: The 389 Directory Server Creation Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: Called with: Namespace(verbose=True, json=False, file='/scratch/ds-foo.inf', dryrun=False, func=<function instance_create at 0x7fb1712c78b0>)
DEBUG: Running setup with verbose
DEBUG: Using inf from /scratch/ds-foo.inf
DEBUG: Configuration ['general', 'slapd', 'backend-userroot']
DEBUG: general:config_version not in inf, using default
DEBUG: general:defaults not in inf, using default
DEBUG: Configuration general {'config_version': 2, 'full_machine_name': 'ldap', 'strict_host_checking': False, 'selinux': False, 'systemd': False, 'start': False, 'defaults': '999999999'}
DEBUG: slapd:user not in inf, using default
DEBUG: slapd:group not in inf, using default
DEBUG: slapd:root_dn not in inf, using default
DEBUG: slapd:prefix not in inf, using default
DEBUG: slapd:secure_port not in inf, using default
DEBUG: slapd:self_sign_cert_valid_months not in inf, using default
DEBUG: slapd:bin_dir not in inf, using default
DEBUG: slapd:sbin_dir not in inf, using default
DEBUG: slapd:sysconf_dir not in inf, using default
DEBUG: slapd:initconfig_dir not in inf, using default
DEBUG: slapd:data_dir not in inf, using default
DEBUG: slapd:local_state_dir not in inf, using default
DEBUG: slapd:lib_dir not in inf, using default
DEBUG: slapd:cert_dir not in inf, using default
DEBUG: slapd:config_dir not in inf, using default
DEBUG: slapd:inst_dir not in inf, using default
DEBUG: slapd:backup_dir not in inf, using default
DEBUG: slapd:db_dir not in inf, using default
DEBUG: slapd:db_home_dir not in inf, using default
DEBUG: slapd:ldif_dir not in inf, using default
DEBUG: slapd:lock_dir not in inf, using default
DEBUG: slapd:log_dir not in inf, using default
DEBUG: slapd:run_dir not in inf, using default
DEBUG: slapd:schema_dir not in inf, using default
DEBUG: slapd:tmp_dir not in inf, using default
DEBUG: Configuration slapd {'port': 389, 'initconfig_dir': '/etc/sysconfig', 'root_password': '12345678', 'secure_port': 636, 'user': 'dirsrv', 'instance_name': 'testds', 'root_dn': 'cn=Directory Manager', 'self_sign_cert': False, 'self_sign_cert_valid_months': 24, 'group': 'dirsrv', 'prefix': '/usr', 'bin_dir': '/usr/bin', 'sbin_dir': '/usr/sbin', 'sysconf_dir': '/etc', 'data_dir': '/usr/share', 'local_state_dir': '/var', 'lib_dir': '/usr/lib64', 'cert_dir': '/etc/dirsrv/slapd-testds', 'config_dir': '/etc/dirsrv/slapd-testds', 'inst_dir': '/usr/lib64/dirsrv/slapd-testds', 'backup_dir': '/var/lib/dirsrv/slapd-testds/bak', 'db_dir': '/var/lib/dirsrv/slapd-testds/db', 'db_home_dir': '/var/lib/dirsrv/slapd-testds/db', 'ldif_dir': '/var/lib/dirsrv/slapd-testds/ldif', 'lock_dir': '/var/lock/dirsrv/slapd-testds', 'log_dir': '/var/log/dirsrv/slapd-testds', 'run_dir': '/var/run/dirsrv', 'schema_dir': '/etc/dirsrv/slapd-testds/schema', 'tmp_dir': '/tmp'}
DEBUG: backend-userroot:suffix not in inf, using default
DEBUG: backend-userroot:sample_entries not in inf, using default
DEBUG: backend-userroot:require_index not in inf, using default
DEBUG: Configuration backends []
DEBUG: START: Starting installation ...
DEBUG: READY: Preparing installation for testds...
INFO: Validate installation settings ...
DEBUG: PASSED: using config settings 999999999
DEBUG: PASSED: user / group checking
DEBUG: PASSED: prefix checking
DEBUG: list instance not found in /etc/dirsrv/slapd-testds/dse.ldif: testds

DEBUG: PASSED: instance checking
DEBUG: INFO: temp root password set to tMjxlEajnaiLwDqPk.FHG.kLlsSAzx3.ZbaCS6K6xpTYOMwqMED6qr0qqnbw0UNae
DEBUG: PASSED: root user checking
DEBUG: PASSED: network avaliability checking
DEBUG: READY: Beginning installation for testds...
DEBUG: ACTION: Creating dse.ldif
INFO: Create file system structures ...
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-testds/bak
DEBUG: ACTION: creating /etc/dirsrv/slapd-testds
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-testds/db
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-testds/ldif
DEBUG: ACTION: creating /var/lock/dirsrv/slapd-testds
DEBUG: ACTION: creating /var/log/dirsrv/slapd-testds
DEBUG: ACTION: creating /var/run/dirsrv
DEBUG: ACTION: Creating certificate database is /etc/dirsrv/slapd-testds
DEBUG: Allocate <class 'lib389.DirSrv'> with None
DEBUG: Allocate <class 'lib389.DirSrv'> with /var/run/slapd-testds.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with localhost:389
DEBUG: Allocate <class 'lib389.DirSrv'> with localhost:389
DEBUG: nss cmd: /usr/bin/certutil -N -d /etc/dirsrv/slapd-testds -f /etc/dirsrv/slapd-testds/pwdfile.txt
DEBUG: nss output: 
DEBUG: systemd status -> True
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
DEBUG: systemd status -> True
DEBUG: Command '['systemctl', 'start', 'dirsrv@testds']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/sbin/dscreate", line 80, in <module>
    result = args.func(inst, log, args)
  File "/usr/lib/python3.9/site-packages/lib389/cli_ctl/instance.py", line 68, in instance_create
    if sd.create_from_inf(args.file):
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 538, in create_from_inf
    self.create_from_args(general, slapd, backends, self.extra)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 913, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 1091, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemctl', 'start', 'dirsrv@testds']' returned non-zero exit status 1.
ERROR: Error: Command '['systemctl', 'start', 'dirsrv@testds']' returned non-zero exit status 1.
```

Apparently this is because it attempts to start the server using `systemd` despite having speficied `start=False` in the .INF file.

Is this a bug? Is there any way I can prevent this?

Starting the server afterwards looks like it works (`ns-slapd -D /etc/dirsrv/slapd-testds/`), although I couldn't successfully test for functionality yet:

```
$ ps ax
    PID TTY      STAT   TIME COMMAND
      1 pts/0    Ss     0:00 /bin/bash
    690 ?        Sl     0:00 ns-slapd -D /etc/dirsrv/slapd-testds/
    716 pts/0    R+     0:00 ps ax
```

**Comment by codedump** [comment]
Replying to my own comment: apparently `/usr/libexec/dirsrv/dscontainer --help` will spin up a barebones 389-ds instance in a container. There is some documentatino [here](https://github.com/389ds/389-ds-base/issues/5452) and [here](https://directory.fedoraproject.org/docs/389ds/design/docker.html), but given that I've spent a substantial amount of time finding that documentation, maybe linking it into a more prominent place wouldn't hurt? (E.g. [here](https://directory.fedoraproject.org/docs/389ds/documentation.html)?)

Thanks & Cheers
