### ISSUE TITLE
Random crash in connection code during server shutdown.

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5478]
**Issue Description**
I saw some pytest failure because the server crashed during shutdown.
gdb on core shows:
#7  0x0000000000437782 in connection_table_get_first_active_connection (ct=ct@entry=0x0, listnum=listnum@entry=0) at /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/conntable.c:318
#8  0x000000000043a4ec in handle_pr_read_ready (num_poll=0, list_num=0, ct=0x0) at /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:1583
#9  ct_list_thread (threadnum=<optimized out>) at /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:1306
#10 0x00007fe587be8413 in _pt_root (arg=0x6120000d5640) at ../../../../nspr/pr/src/pthreads/ptthread.c:201
#11 0x00007fe58848ce2d in start_thread (arg=<optimized out>) at pthread_create.c:442
#12 0x00007fe5885121b0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

libasan says:
==628804==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x000000437782 bp 0x7f87805ed910 sp 0x7f87805ed910 T6)
==628804==The signal is caused by a READ memory access.
==628804==Hint: address points to the zero page.

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x437782 in connection_table_get_first_active_connection /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/conntable.c:318
    #1 0x43a4eb in handle_pr_read_ready /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:1583
    #2 0x43a4eb in ct_list_thread /home/progier/sb/i5408/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:1306
    #3 0x7f88097fc412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #4 0x7f8809c8ce2c in start_thread (/lib64/libc.so.6+0x8ce2c)
    #5 0x7f8809d121af in clone3 (/lib64/libc.so.6+0x1121af)

**Package Version and Platform:**
 Fedora / main branch  an 2.2 branch (2.1 is not impacted)

**Steps to Reproduce**
1. Run pytest test_import_duplicate_dn in loop
2. It should always PASS but sometime it fails 

**Expected results**
All test show PASS and no core dump should be spawned.

**Additional context**
Root cause is that the connection table get freed while the ct_list_thread is still working on it.

**Comment by progier389** [comment]
cd0bd6005894853bd22f711d915e5bc7cf415e24
   469e856ca..cd0bd6005  main -> main
   76a6f168b..2a2262723  389-ds-base-2.2 -> 389-ds-base-2.2
