### ISSUE TITLE
A random crash may occurs while importing an ldif fdile in lmdb database.

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5545]
**Issue Description**

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch

**Steps to Reproduce**
1. Generate a 10 000 000 users ldif file
2. Set up a server using lmdb
3. Import the ldif file
4. See error: (import fails and core is dumped)

**Expected results**
Import should complete without crashing

**Additional context**

A random crash may occurs while importing an ldif fdile in lmdb database.
Note: on 3 run while trying to import 10M entries I got the crash after importing 5M, 9.5M, 0.1M entries (so very random but not frequent)

Core was generated by `/root/pierre_do_not_remove/dsroot/sbin/ns-slapd ldif2db -D /root/pierre_do_not_'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f69847c8528 in dbmdb_import_prepare_worker_entry (wqelmnt=0x111e330) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:1309
1309    ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5cfd8b0700 (LWP 29973))]
(gdb) where
#0  0x00007f69847c8528 in dbmdb_import_prepare_worker_entry (wqelmnt=0x111e330) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:1309
#1  0x00007f69847ca902 in dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3155
#2  0x00007f698d2c3968 in _pt_root (arg=0x1116d90) at ../../.././nspr/pr/src/pthreads/ptthread.c:201
#3  0x00007f698cc5e1cf in start_thread (arg=<optimized out>) at pthread_create.c:479
#4  0x00007f698f685dd3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) x /i 0x00007f69847c8528
=> 0x7f69847c8528 <dbmdb_import_prepare_worker_entry+168>:  repz cmpsb %es:(%rdi),%ds:(%rsi)
(gdb) print $es
$1 = 0
(gdb) print $rdi
$2 = 140091171154120
(gdb) print $ds
$3 = 0
(gdb) print %rsi
A syntax error in expression, near `%rsi'.
(gdb) print $rsi
$4 = 0
(gdb) x /s 140091171154120
0x7f69847e28c8: "version:"
(gdb) p wqelmnt->data
$5 = (void *) 0x7f5cf45db070

mdb_import_threads.c:1309 is:
    if (0 == ctx->wgc.version_found && 0 == strncmp(estr, "version:", 8)) {

so the crash occurs because estr is null (
 apparently a race condition issue because estr is wqelmnt->data which is
 not NULL at the crash time )

**Comment by progier389** [comment]
Cherry-picked LMDB changes to 2.1 to fix the CLANG compile errors #5484:

6a78c9f5a0d9f922cdaf524712cdb6dd93a670d2 Issue 5408: lmdb import is slow (#5481)
   764a306e4..ce0ff7375  389-ds-base-2.2 -> 389-ds-base-2.2
   9476a78e3..539a29bdc  389-ds-base-2.1 -> 389-ds-base-2.1

4b82bf6d391ef12069e101ba2161ed0a25bbaba5 Issue 5490 - tombstone in entryrdn index with lmdb but not with bdb (#5498)
   ce0ff7375..067ec8134  389-ds-base-2.2 -> 389-ds-base-2.2
   539a29bdc..06bcbd913  389-ds-base-2.1 -> 389-ds-base-2.1

bb5df9d474d9cf9f224c90d8171b95e5042bedf5 Issue 5545 - A random crash in import over lmdb (#5546)
   067ec8134..acee4ca7c  389-ds-base-2.2 -> 389-ds-base-2.2
   06bcbd913..9d92f6a86  389-ds-base-2.1 -> 389-ds-base-2.1
