### ISSUE TITLE
 dsidm account subtree-status fails with TypeError 

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5593]
**Issue Description**

Running "dsidm account subtree-status" command fails with TypeError.

**Steps to Reproduce**

    #  dsidm -D "cn=Directory Manager" ldap://localhost -b "dc=example,dc=com" account subtree-status "ou=People,dc=example,dc=com" -f "(uid=*)"

Actual results:

DEBUG: expected list of strings or None
Traceback (most recent call last):
  File "/usr/sbin/dsidm", line 140, in <module>
    result = args.func(inst, dsrc_inst['basedn'], log, args)
  File "/usr/lib/python3.9/site-packages/lib389/cli_idm/account.py", line 87, in subtree_status
    account_list = Accounts(inst, basedn).filter(filter, scope)
  File "/usr/lib/python3.9/site-packages/lib389/_mapped_object.py", line 1264, in filter
    results = self._instance.search_ext_s(
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 174, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 863, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 174, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 853, in search_ext
    return self._ldap_call(
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 174, in inner
    return f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
TypeError: expected list of strings or None
ERROR: Error: expected list of strings or None

**Comment by mreynolds389** [comment]
8fa65330f..c81ee3486  389-ds-base-2.2 -> 389-ds-base-2.2
bc03cb9bd..9398b8656  389-ds-base-2.1 -> 389-ds-base-2.1
a63e22627..ff6dbd909  389-ds-base-2.0 -> 389-ds-base-2.0
be8e4189c..74ebe9873  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
