### ISSUE TITLE
Memory leak in entryrdn during delete

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5643]
**Issue Description**

 Delete op triggers memory leak:

```
Direct leak of 96 byte(s) in 3 object(s) allocated from:
    #0 0x7f5c708ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f5c70f1faee in GrowStuff (/lib64/libnspr4.so+0x12aee)
    #2 0x7f5c70f1f865 in fill_n (/lib64/libnspr4.so+0x12865)
    #3 0x7f5c70f2049e in dosprintf (/lib64/libnspr4.so+0x1349e)
    #4 0x7f5c70f20db2 in PR_vsmprintf (/lib64/libnspr4.so+0x13db2)
    #5 0x7f5c7005d87c in slapi_ch_smprintf (/usr/lib64/dirsrv/libslapd.so.0+0x25d87c)
    #6 0x7f5c6a105693 in entryrdn_delete_key ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c:2700
    #7 0x7f5c6a106621 in entryrdn_index_entry ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c:252
    #8 0x7f5c6a0d0d82 in index_addordel_entry ldap/servers/slapd/back-ldbm/index.c:487
    #9 0x7f5c6a1076ec in ldbm_back_delete ldap/servers/slapd/back-ldbm/ldbm_delete.c:811
    #10 0x7f5c700920c2 in op_shared_delete ldap/servers/slapd/delete.c:338
    #11 0x7f5c70092832 in do_delete (/usr/lib64/dirsrv/libslapd.so.0+0x292832)
    #12 0x55639e2812e6 in connection_dispatch_operation ldap/servers/slapd/connection.c:643
    #13 0x55639e2812e6 in connection_threadmain ldap/servers/slapd/connection.c:1805
    #14 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #15 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #16 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)
```

**Comment by mreynolds389** [comment]
9c05f2e46..2a27121f1  389-ds-base-2.3 -> 389-ds-base-2.3
aa1d1a998..09236fb2d  389-ds-base-2.2 -> 389-ds-base-2.2
f6e226ec8..cd3d6241e  389-ds-base-2.1 -> 389-ds-base-2.1
