### ISSUE TITLE
Various memory leaks

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5646]
**Issue Description**

```
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c708ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7f5c7006ac25 in slapi_ch_calloc (/usr/lib64/dirsrv/libslapd.so.0+0x26ac25)
    #2 0x7f5c7006b7a1 in get_ldapmessage_controls_ext (/usr/lib64/dirsrv/libslapd.so.0+0x26b7a1)
    #3 0x55639e2aadee in do_search ldap/servers/slapd/search.c:349
    #4 0x55639e2813fe in connection_dispatch_operation ldap/servers/slapd/connection.c:677
    #5 0x55639e2813fe in connection_threadmain ldap/servers/slapd/connection.c:1805
    #6 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #7 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #8 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)


Indirect leak of 25 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c708ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f5c70fc6ed4 in ber_memalloc_x (/lib64/liblber.so.2+0x6ed4)
    #2 0x7f5c70fc6f98 in ber_get_stringbv (/lib64/liblber.so.2+0x6f98)
    #3 0x7f5c70fc734d in ber_get_stringa (/lib64/liblber.so.2+0x734d)
    #4 0x7f5c70fc9820 in ber_scanf (/lib64/liblber.so.2+0x9820)
    #5 0x7f5c7006b813 in get_ldapmessage_controls_ext (/usr/lib64/dirsrv/libslapd.so.0+0x26b813)
    #6 0x55639e2aadee in do_search ldap/servers/slapd/search.c:349
    #7 0x55639e2813fe in connection_dispatch_operation ldap/servers/slapd/connection.c:677
    #8 0x55639e2813fe in connection_threadmain ldap/servers/slapd/connection.c:1805
    #9 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #10 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #11 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c708ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7f5c7006ac25 in slapi_ch_calloc (/usr/lib64/dirsrv/libslapd.so.0+0x26ac25)
    #2 0x7f5c69ccbfc6 in supplier_operation_extension_constructor ldap/servers/plugins/replication/repl_opext.c:25
    #3 0x7f5c700b9407 in factory_create_extension (/usr/lib64/dirsrv/libslapd.so.0+0x2b9407)
    #4 0x55639e26d5a2 in connection_add_operation ldap/servers/slapd/connection.c:2086
    #5 0x55639e26d5a2 in connection_activity ldap/servers/slapd/connection.c:1941
    #6 0x55639e273281 in handle_pr_read_ready ldap/servers/slapd/daemon.c:1617
    #7 0x55639e273281 in ct_list_thread ldap/servers/slapd/daemon.c:1302
    #8 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #9 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #10 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c7087243b in strdup (/lib64/libasan.so.8+0x7243b)
    #1 0x7f5c7006c1bd in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x26c1bd)
    #2 0x7f5c700887f4 in ndn_cache_lookup ldap/servers/slapd/dn.c:2948
    #3 0x7f5c700887f4 in slapi_dn_normalize_ext ldap/servers/slapd/dn.c:546
    #4 0x7f5c7008eafc in slapi_sdn_get_dn (/usr/lib64/dirsrv/libslapd.so.0+0x28eafc)
    #5 0x55639e2802e1 in connection_dispatch_operation ldap/servers/slapd/connection.c:605
    #6 0x55639e2802e1 in connection_threadmain ldap/servers/slapd/connection.c:1805
    #7 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #8 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #9 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c7087243b in strdup (/lib64/libasan.so.8+0x7243b)
    #1 0x7f5c7006c1bd in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x26c1bd)
    #2 0x7f5c7008f8c9 in slapi_sdn_set_dn_byval (/usr/lib64/dirsrv/libslapd.so.0+0x28f8c9)
    #3 0x55639e280eee in op_copy_identity ldap/servers/slapd/connection.c:2174
    #4 0x55639e280eee in connection_dispatch_operation ldap/servers/slapd/connection.c:559
    #5 0x55639e280eee in connection_threadmain ldap/servers/slapd/connection.c:1805
    #6 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #7 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #8 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c7087243b in strdup (/lib64/libasan.so.8+0x7243b)
    #1 0x7f5c7006c1bd in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x26c1bd)
    #2 0x7f5c7008f1fd in slapi_sdn_get_ndn (/usr/lib64/dirsrv/libslapd.so.0+0x28f1fd)
    #3 0x7f5c7008f34f in slapi_sdn_issuffix (/usr/lib64/dirsrv/libslapd.so.0+0x28f34f)
    #4 0x7f5c7010ddbf in best_matching_child ldap/servers/slapd/mapping_tree.c:2727
    #5 0x7f5c70112be6 in slapi_mapping_tree_select_all ldap/servers/slapd/mapping_tree.c:2232
    #6 0x7f5c70138551 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x338551)
    #7 0x55639e2ab19f in do_search ldap/servers/slapd/search.c:410
    #8 0x55639e2813fe in connection_dispatch_operation ldap/servers/slapd/connection.c:677
    #9 0x55639e2813fe in connection_threadmain ldap/servers/slapd/connection.c:1805
    #10 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #11 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #12 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c7087243b in strdup (/lib64/libasan.so.8+0x7243b)
    #1 0x7f5c7006c1bd in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x26c1bd)
    #2 0x7f5c7009027d in slapi_sdn_set_normdn_byval (/usr/lib64/dirsrv/libslapd.so.0+0x29027d)
    #3 0x7f5c70090330 in slapi_sdn_new_normdn_byval (/usr/lib64/dirsrv/libslapd.so.0+0x290330)
    #4 0x7f5c70127cd2 in operation_set_target_spec (/usr/lib64/dirsrv/libslapd.so.0+0x327cd2)
    #5 0x7f5c70137fe1 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x337fe1)
    #6 0x55639e2ab19f in do_search ldap/servers/slapd/search.c:410
    #7 0x55639e2813fe in connection_dispatch_operation ldap/servers/slapd/connection.c:677
    #8 0x55639e2813fe in connection_threadmain ldap/servers/slapd/connection.c:1805
    #9 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #10 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #11 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5c708ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7f5c7006ac25 in slapi_ch_calloc (/usr/lib64/dirsrv/libslapd.so.0+0x26ac25)
    #2 0x7f5c69ccddd5 in consumer_operation_extension_constructor ldap/servers/plugins/replication/repl_opext.c:54
    #3 0x7f5c700b9407 in factory_create_extension (/usr/lib64/dirsrv/libslapd.so.0+0x2b9407)
    #4 0x55639e26d5a2 in connection_add_operation ldap/servers/slapd/connection.c:2086
    #5 0x55639e26d5a2 in connection_activity ldap/servers/slapd/connection.c:1941
    #6 0x55639e273281 in handle_pr_read_ready ldap/servers/slapd/daemon.c:1617
    #7 0x55639e273281 in ct_list_thread ldap/servers/slapd/daemon.c:1302
    #8 0x7f5c70f39412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #9 0x7f5c6fa8cdec in start_thread (/lib64/libc.so.6+0x8cdec)
    #10 0x7f5c6fb1236f in clone3 (/lib64/libc.so.6+0x11236f)


```

These can be found running with ASAN:

LSAN_OPTIONS=exitcode=0:log_threads=1:verbosity=1 PYINSTALL=1 py.test basic_test.py::test_sync_repl_cookie_add_del

**Comment by mreynolds389** [comment]
Don't forget to backport these commits to all the branches where it applies :-)

**Comment by jchapma** [comment]
8a40743d9..6f8bfb74c  389-ds-base-2.3 -> 389-ds-base-2.3
b7ed55e1b..96e839979  389-ds-base-2.2 -> 389-ds-base-2.2
498debffb..87145a765  389-ds-base-2.1 -> 389-ds-base-2.1
f8622f6ad..9072a18a6  389-ds-base-2.0 -> 389-ds-base-2.0
8fde790b6..df6d9321c  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
4c16b43c7..58d09ebe2  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
