### ISSUE TITLE
Libasan crash in replication/cascading_test

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5652]
**Issue Description**
got a crash when running replication/cascading_test on with an asan build.
```
==3011829==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fe164ea3c98 at pc 0x7fe1e6ae5131 bp 0x7fe164ea3b20 sp 0x7fe164ea3b18
READ of size 8 at 0x7fe164ea3c98 thread T25
    #0 0x7fe1e6ae5130 in decode_startrepl_extop /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/plugins/replication/repl_extop.c:486
    #1 0x7fe1e6ae5130 in multisupplier_extop_StartNSDS50ReplicationRequest /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/plugins/replication/repl_extop.c:699
    #2 0x7fe1ecd4a467 in plugin_call_exop_plugins /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/slapd/plugin.c:511
    #3 0x44364a in do_extended /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/slapd/extendop.c:445
    #4 0x43381f in connection_dispatch_operation /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/slapd/connection.c:707
    #5 0x43381f in connection_threadmain /home/progier/sb/i5628/tst/source/389-ds-base/ldap/servers/slapd/connection.c:1805
    #6 0x7fe1ec2da412 in _pt_root (/lib64/libnspr4.so+0x2c412)
    #7 0x7fe1ec68cdcc in start_thread (/lib64/libc.so.6+0x8cdcc)
    #8 0x7fe1ec71262f in __GI___clone3 (/lib64/libc.so.6+0x11262f)

```
And the code 
```
        for (size_t i = 0; *extra_referrals && extra_referrals[i]; i++) {
            slapi_log_err(SLAPI_LOG_REPL, repl_plugin_name, "decode_startrepl_extop - "
                "decoded referral: %s\n", *extra_referrals[i]);
        }

``` 
seems suspicious: it should be:
```
 for (size_t i = 0; *extra_referrals && (*extra_referrals)[i]; i++) {
            slapi_log_err(SLAPI_LOG_REPL, repl_plugin_name, "decode_startrepl_extop - "
                "decoded referral: %s\n", (*extra_referrals)[i]);
        }
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version:  main branch

**Steps to Reproduce**
1. Run replication/cascading_test CI test with an asan build.

**Expected results**
No crash

**Comment by mreynolds389** [comment]
I think this needs to be back ported all the way down to 1.4.3...

**Comment by progier389** [comment]
9710cf1c34f554ea0c7449f0b450b5cc26bb1a43
   e4ed5a8a5..9710cf1c3  main -> main
   27bf3a348..ad73687fc  389-ds-base-2.2 -> 389-ds-base-2.2
   8af9eb068..838a9f260  389-ds-base-2.1 -> 389-ds-base-2.1
   74c731a02..b09a460db  389-ds-base-2.0 -> 389-ds-base-2.0
   Note: 1.4.4 does not contain the buggy code.
   9b26ccebc..a46160c90  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
