### ISSUE TITLE
CLI - allow dsconf to specify a timeout for tasks

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5666]
**Issue Description**

In lib389/tasks.py, there is a timeout of 120 * 2 seconds ( 4 minutes ) when a new task is created.
In case the task takes longer, dsconf returns the following message:

```
DEBUG: The backup create task has failed with the error code: (None)
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 134, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.6/site-packages/lib389/cli_conf/backup.py", line 20, in backup_create
    raise ValueError("The backup create task has failed with the error code: ({})".format(result))
ValueError: The backup create task has failed with the error code: (None)
```

It would be nice to:
* allow dsconf to specify a timeout ( maybe this is already possible but I don't see any documented option )
* provide additional information stating that the timeout was over.

**Comment by mreynolds389** [comment]
fa344b9e9..26eaa1b7d  389-ds-base-2.2 -> 389-ds-base-2.2
c58c5d14a..7891c5f12  389-ds-base-2.1 -> 389-ds-base-2.1
3242ae640..f8aca8e88  389-ds-base-2.0 -> 389-ds-base-2.0
d77fe854b..35b76e0a7  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
