### ISSUE TITLE
Referral mode is not working

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5701]
Description of problem:

Referral mode not working and failing with error: ERROR: Error: 103 - 10 - 53 - Server is unwilling to perform - [] -
need to set nsslapd-referral

How reproducible:
Every time

Steps to Reproduce:
1. Create two instances

2. Stop the instance on the host you want to redirect:

```
# systemctl stop dirsrv@instance_name
```

3. Run ns-slapd in referral mode:

```
# ns-slapd refer -D /etc/dirsrv/slapd-instance_name [-p port] -r referral_url
```

4.Even though nsslapd-referral is set:

```
cn=data_on_1,cn=ldbm database,cn=plugins,cn=config
...
nsslapd-referral: ldap://localhost:38902/ou=people,dc=example,dc=com
```

Updating the state doesn't work:

```# dsconf -v instance1 backend suffix set --state referral
ou=data_on_instance1,dc=example,dc=com
...
ldap.UNWILLING_TO_PERFORM: {'msgtype': 103, 'msgid': 10, 'result': 53,
'desc': 'Server is unwilling to perform', 'ctrls': [], 'info': 'need
to set
 nsslapd-referral before moving to referral state\n'}
```

**Comment by droideck** [comment]
Before the issue is fixed/can be tested (and it's possible that it's already fixed), we need to fix another bug around the area:
```
DEBUG: 'BackendSuffixView' object has no attribute 'set_state'
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 139, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/local/lib/python3.9/site-packages/lib389/cli_conf/backend.py", line 510, in backend_set
    bev.set_state(args.state)
  File "/usr/local/lib/python3.9/site-packages/lib389/_mapped_object.py", line 244, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
AttributeError: 'BackendSuffixView' object has no attribute 'set_state'
ERROR: Error: 'BackendSuffixView' object has no attribute 'set_state'
```

It happens because we've added 'set_state' in one commit, but then we've started to use another object in CLI tools BackendSuffixView which doesn't have the 'set_state': 
https://github.com/389ds/389-ds-base/commit/9d0c9b886e0800a285f6964760a34170f7abf5b1
https://github.com/389ds/389-ds-base/commit/83b3fe968a45cc43c826bb89a3c5541bc8f452e5

**Comment by droideck** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2053204
