### ISSUE TITLE
dsconf monitor backend fails on lmdb

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5833]
**Issue Description**
 Several issues probably related to the same root cause:
 - LMDB WebUI CI Test fails 
 - Cockpit Suffix Monitor Information page hangs
 - dsconf instance monitor backend  bename Fails:
 -  
**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch
 - Browser: chrome

**Steps to Reproduce**
1. Install a DS  instance using lmdb
2. run dsconf instance monitor backend  userroot
3. See error:
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 139, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.10/site-packages/lib389/cli_conf/monitor.py", line 30, in backend_monitor
    _format_status(log, be_monitor, args.json)
  File "/usr/lib/python3.10/site-packages/lib389/cli_base/__init__.py", line 175, in _format_status
    status_dict = mtype.get_status()
  File "/usr/lib/python3.10/site-packages/lib389/monitor.py", line 330, in get_status
    result[attr] = all_attrs[attr]
KeyError: 'dncachehits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 149, in <module>
    log.error("Error: %s" % " - ".join(str(val) for val in msg.values()))
AttributeError: 'str' object has no attribute 'values'
[root@linux slapd]# 

**Expected results**
 -  dsconf instance monitor backend  bename should not fails
 - Cockpit page should not hang
 - And hopefully CI test should be ok 

**Additional context**
dn cache still exists in lmdb cache so statistics should be available but the following attribute are missing for lmdb in:
search under  "cn=monitor,cn=userroot,cn=ldbm database,cn=plugins,cn=config"

currentdncachesize: 339
maxdncachesize: 738197504
currentdncachecount: 5
maxdncachecount: -1

IMHO a change done on bdb while I worked on lmdb and the associated change was not added in db-mdb folder ...

**Comment by progier389** [comment]
9851f0ab1..f4f83eab6  main -> main
   9e6979e31..dc0c78ba5  389-ds-base-2.3 -> 389-ds-base-2.3
   7fbf7bbbd..ea8d94b83  389-ds-base-2.2 -> 389-ds-base-2.2
   1cdd011eb..441951ba6  389-ds-base-2.1 -> 389-ds-base-2.1
