### ISSUE TITLE
`test_basic_ldapagent` breaks test_setup_ds_as_non_root* tests

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5877]
**Issue Description**
`test_basic_ldapagent` creates non-readable by others `agent.conf` file:
```
# ls /etc/dirsrv/config/ -la
total 28
drwxr-xr-x. 2 root root    96 Aug  1 09:02 .
drwxr-xr-x. 6 root root    71 Aug  1 09:09 ..
-rw-rw----. 1 root root    91 Aug  1 09:02 agent.conf
-rw-r--r--. 1 root root  1676 May 22 08:44 certmap.conf
-rw-r--r--. 1 root root  1006 May 22 08:44 ldap-agent.conf
-rw-r--r--. 1 root root 15142 May 22 08:44 slapd-collations.conf
```

It also doesn't delete it after the test is finished.

This breaks `test_setup_ds_as_non_root*` tests, since `dscreate ds-root` tries to copy everything under `/etc/dirsrv/config` to a non-root user directory and fails:

```
+ dscreate ds-root /home/user1/test_setup_ds_as_non_root_with_default_options/root /home/user1/test_setup_ds_as_non_root_with_default_options/bin
Traceback (most recent call last):
  File "/usr/sbin/dscreate", line 99, in <module>
    result = args.func(inst, log, args)
  File "/usr/local/lib/python3.9/site-packages/lib389/cli_ctl/instance.py", line 220, in prepare_ds_root
    copytree(dir, destdir, dirs_exist_ok=True)
  File "/usr/lib64/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [('/etc/dirsrv/config/agent.conf', '/home/user1/test_setup_ds_as_non_root_with_default_options/root//etc/dirsrv/config/agent.conf', "[Errno 13] Permission denied: '/etc/dirsrv/config/agent.conf'")]
```

**Comment by vashirov** [comment]
We don't see this breakage in GH CI because each test suite is executed separately, but when all test suites are ran on the same machine, they can affect execution of the other test suite(s).

**Comment by vashirov** [comment]
744cb41df..edb43569f  389-ds-base-2.0 -> 389-ds-base-2.0
   86c736baa..2c35f7309  389-ds-base-2.1 -> 389-ds-base-2.1
   8d74381b0..143ea6530  389-ds-base-2.2 -> 389-ds-base-2.2
   bd3140f24..ca41bf590  389-ds-base-2.3 -> 389-ds-base-2.3
