### ISSUE TITLE
ASAN server build crash when looping opening/closing connections 

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5924]
**Issue Description**
Get a crash with following stack when doing an ldapmodify loop  targeted to ldapi port

```
 Crash signature is:
==1861306==ERROR: AddressSanitizer: SEGV on unknown address 0x001f00096fe2 (pc 0x7f00639213c7 bp 0x7effb6f70920 sp 0x7effb6f706a0 T31)
==1861306==The signal is caused by a READ memory access.
#0 0x7f00639213c7 in _pr_poll_with_poll (/lib64/libnspr4.so+0x283c7) (BuildId: 274218d7d2f6b1532ca85ca6dcfca4a47312cc54)
#1 0x43de56 in accept_thread /home/progier/sb/389/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:843
#2 0x7f0063926738 in _pt_root (/lib64/libnspr4.so+0x2d738) (BuildId: 274218d7d2f6b1532ca85ca6dcfca4a47312cc54)
#3 0x7f0063dd1906 in start_thread (/lib64/libc.so.6+0x8c906) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
#4 0x7f0063e5786f in __clone3 (/lib64/libc.so.6+0x11286f) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
```

One of the cause is because the listening file descriptor is closed instead of the accepted file descriptor 
 reading the code, I see that the variable names are misleading and there was a confusion.
The other cause is why are we unable to get a connection slot while only a single connection is open ?

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 
       Isuue reproduce on:
           -  389-ds-base-2.2
           - main branches
        But not on: 
           -  389-ds-base-2.1
           -  389-ds-base-4.3.1

**Steps to Reproduce**

Use the following script:
```
#!/bin/bash

INAME=scrdl
P="$PREFIX/var/run/slapd-$INAME.socket"
URI="ldapi://$(echo $P | sed 's,/,%2f,g')"

#Limit the connection table size to speed up the test
ulimit  -n 256
ulimit -H -n 256

# remove the previous instance if running again the test
$PREFIX/usr/sbin/dsctl $INAME remove --do-it >/dev/null 2>&1

# Create ds instance (make sure to disable systemctl
#  to insure that ns-slapd is a children of this shell script)
echo "
[general]
systemd = False
[slapd]
instance_name = $INAME
sample_entries = yes
[backend-userroot]
suffix = dc=example,dc=com
create_suffix_entry = yes
" > /tmp/ds.conf
$PREFIX/usr/sbin/dscreate from-file /tmp/ds.conf || exit 1
/bin/rm -f /tmp/ds.conf

# Then loops doing a modify operation
echo "Configuration is complete. Infinite loop is starting."

n=0
set -e
while :
do
    let n=n+1
    echo "Loop #$n"
    ldapmodify -Q -Y EXTERNAL -H "$URI" <<!
dn: dc=example, dc=com
changetype: modify
replace: description
description: `date`
!
done

```

The test stops after a few minutes:
Loop #190
modifying entry "dc=example, dc=com"

Loop #191
ldap_sasl_interactive_bind: Can't contact LDAP server (-1)

[389-ds-base]$coredumpctl
TIME                             PID    UID  GID SIG     COREFILE EXE                                                  >
Thu 2023-09-07 12:04:45 CEST 1572010 117643 5977 SIGABRT present  /home/progier/sb/389/tst/ci-install/sbin/ns-slapd    >

**Additional information**
I was doing my test on a build with libasan.
According to my tests with RHEL 9.3, the symptoms are very different when using the standard build:
  Using the test case proposed in the PR:
                  Test successful  for 1 (the default value) and 2 listeners
                  Test fails (no crash but server got unresponsive on the tested (ldapi) port) for 3 or 4 listeners)

**Comment by progier389** [comment]
Second issue is related to the freelist handling:
1. Last freelist slots are not initialized and when hitting these slot, the connection table is supposed to be exhausted.
    but it should reset the index in that case
 2. I think that the current freelist handling is wrong as it uses a new slot for each connections.
 Putting freed connection just before the head (i.e decreasing the index) seems much simple (only needs a single index and no need to handle the array boundary: if NULL pointer is reached, this really means that connection table is exhausted. )
 3. There are no reason to skip freelist[0] the freelist is an array of connection slots ...

**Comment by progier389** [comment]
The test failed in CI test.  I think it is because the wrapper is written in /tmp 
  ( will try to write it in $HOME instead )

**Comment by progier389** [comment]
9633e8d32..02d333251  main -> main
530890806..26716f0ed  389-ds-base-2.3 -> 389-ds-base-2.3
9c75a6ced..c44f17328  389-ds-base-2.2 -> 389-ds-base-2.2
