### ISSUE TITLE
Google translate can crash the UI

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5933]
**Issue Description**
When a page is being translated via Chrome's Google Translate integrated browser extension, it can lead to a crash when the page is reloaded after the configuration is saved.

**Package Version and Platform:**
 - Platform: Fedora 38
 - Package and version: 389-ds-base-2.4.3-202309210103git9ce280b82.fc38
 - Browser: Chrome Version 116.0.5845.179 (Official Build) (64-bit)

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Enable Google Translate (right-click on any empty space -> translate to [language])
1. Go to Server Settings -> Advanced Settings
2. Click on one of the checkboxes (for example, `Enable Plugin Bind DN Tracking`)
3. Click "Save Settings"

**Expected results**
Settings are correctly saved.

**Actual results**
Browser crashes, and the next error is displayed in the browser console:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
updates.js:155 Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"不允许执行该操作。"}", data: "undefined"
(anonymous) @ updates.js:155
2index.js:16 One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
render @ index.js:16
index.js:15 CMD: loadInstanceList: Load the instance list select ==> dsctl -l -j
overview.js:134 can't get NTPSynchronized property be
shell.js:8 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at E5 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:25573)
    at sa (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:30799)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27834)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27826)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
B5 @ shell.js:8
shell.js:6 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at E5 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:25573)
    at sa (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:30799)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27834)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27826)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
389-console:1 Refused to load the stylesheet 'https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.qhDXWpKopYk.L.W.O/d=0/rs=AN8SPfp0QXhhaDDdjg_LgcSqoZiPEzC1tw/m=el_main_css' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

VM60:26     POST https://translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT
_.Zg.send @ m=el_conf:586
_.Pi @ VM60:26
tr.send @ VM60:222
r @ VM60:217
eval @ VM60:218
Promise.then (async)
hr.flush @ VM60:217
eval @ VM60:212
Zd @ m=el_conf:521
_.k.dispatchEvent @ m=el_conf:520
Mo.A @ VM60:174
Show 3 more frames
Show less
8updates.js:12 Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
(anonymous) @ updates.js:12
QY @ updates.js:8
UY @ updates.js:8
ALe @ updates.js:8
$I @ updates.js:8
VY @ updates.js:8
aE @ updates.js:1
J3 @ updates.js:1
VM60:26     POST https://translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT
```

**Comment by vashirov** [comment]
> Browser: Chrome Version 116.0.5845.179 (Official Build) (64-bit)

Latest stable is 117.0.5938.88. Could you please check if it happens there as well?
