### ISSUE TITLE
WebUI supports only instances with BDB

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#6065]
**Issue Description**
It's not possible to choose DB backend when a new instance is created.
And for existing instances WebUI expects `dsconf` to return BDB specific parameters. For example, a page throws an Oops... when I navigate to `Database` tab on an instance with LMDB backend:

https://github.com/389ds/389-ds-base/blob/1f95b57fb8b03f72c7d2a2ce5b14eed5ba320407/src/cockpit/389-console/src/database.jsx#L251

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Function.<anonymous> (database.jsx:251:55)
    at process_queue (cockpit.js:1311:37)
    at cockpit.js:1324:35
    at later_drain (cockpit.js:1205:13)
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch
 - Browser: Firefox

**Steps to Reproduce**
1. Create a new instance with MDB backend
2. Go to Database tab
3. Observe an Oops...

**Expected results**
WebUI should support instances with both BDB and LMDB backends and not crash if some attributes are not available.

**Comment by progier389** [comment]
Created IDMDS-4185 ticket
