### ISSUE TITLE
"dsconf replication status" fails with python error

### ISSUE THREAD

**Issue by sschols** [389ds/389-ds-base#6132]
**Issue Description**
We have two 389-ds servers with replication set up between them. Replication has been setup manually, not using dsconf.

When trying to get the replication status via dsconf, we get a python error message:
```
# dsconf ldap01 replication status --suffix dc=ldap,dc=example,dc=local
Error: 'NoneType' object has no attribute 'lower'
```

verbose mode shows the exact issues
```
# dsconf -v ldap01 replication status --suffix dc=ldap,dc=example,dc=local
...
DEBUG: cn=ReplAgreement001,cn=replica,cn=dc\3Dldap\2Cdc\3Dexample\2Cdc\3Dlocal,cn=mapping tree,cn=config getVal('nsds5replicatransportinfo')
DEBUG: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/sbin/dsconf", line 139, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.6/site-packages/lib389/cli_conf/replication.py", line 323, in get_repl_status
    status = replica.status(binddn=args.bind_dn, bindpw=passwd)
  File "/usr/lib/python3.6/site-packages/lib389/replica.py", line 1665, in status
    raw_status = agmt.status(binddn=binddn, bindpw=bindpw, use_json=True, winsync=winsync)
  File "/usr/lib/python3.6/site-packages/lib389/agreement.py", line 346, in status
    lag_time = self.get_lag_time(suffix, agmt_name, binddn=binddn, bindpw=bindpw)
  File "/usr/lib/python3.6/site-packages/lib389/agreement.py", line 281, in get_lag_time
    con_maxcsn = self.get_consumer_maxcsn(binddn=binddn, bindpw=bindpw)
  File "/usr/lib/python3.6/site-packages/lib389/agreement.py", line 148, in get_consumer_maxcsn
    protocol = self.get_attr_val_utf8('nsds5replicatransportinfo').lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

The error seems to come from the "nsds5replicatransportinfo" parameter not being set in the replication agreement. This is correct, it was not set, and once we added it manually, the dsconf command ran smoothly. But from my understanding, the parameter has a default. But according to <https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/configuration_command_and_file_reference/core_server_configuration_reference#Replication_Attributes_under_cnReplicationAgreementName_cnreplica_cnsuffixName_cnmapping_tree_cnconfig-nsDS5ReplicaTransportInfo>, it does not need to be set, and defaults to "LDAP" if no value is in place.

**Package Version and Platform:**
 - Platform: AlmaLinux8
 - Package and version: 389-ds-base-1.4.3.37

**Steps to Reproduce**
* Setup replication manually without "nsds5replicatransportinfo"
* Run "dsconf <instance> replication status --suffix <suffix>

**Expected results**
Get some sort of replication status information

**Additional context**
From my understanding, the problem is here: https://github.com/389ds/389-ds-base/blob/23a094c535d5d4ce7fc94b74359697c666a19426/src/lib389/lib389/agreement.py#L149C2-L150C1 -> There should be some kind of error checking, or defaults magic in place

**Comment by progier389** [comment]
The problem still exists in the main branch.
Should  use  self.get_attr_val_utf8_l() instead of self.get_attr_val_utf8().lower()
