### ISSUE TITLE
Allow systemd to manage uid/gid changes rather than calling setuid.

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#6181]
We have a customer at SUSE who wishes to implement a non-standard configuration in which the running gid is not the primary gid of the uid that the server runs as. Currently this trips up most of our setup tools.

Rather than support dropping to an alternate gid in the server, it is simpler to allow systemd to pre-configure our user and group at start up. This needs a small number of changes.

* dscreate needs to correctly setup file ownships for dse.ldif and friends rather than relying on the server having root access and changing the perms itself
* That our unit file needs to enable the CAP_NET_BIND privilege so that the service can bind to ports lower than 1024 without being root
* That the server needs to *not* attempt to change it's uid/gid if we are already running as that user/gid.

**Comment by Firstyear** [comment]
Needed in 2.2 for our customer.

**Comment by Firstyear** [comment]
2.2.8 specifically :)

**Comment by vashirov** [comment]
This change introduced a regression. On F40 instance creation fails:
```
# echo Yes | dsctl --remove-all; echo -e "[general]\n[slapd]\ninstance_name = localhost\nroot_password = password\nport = 389\nsecure_port = 636\n[backend-userroot]\ncreate_suffix_entry = True\nsample_entries = yes\nsuffix = dc=example,dc=com\n" > /tmp/inst.inf; dscreate -v from-file /tmp/inst.inf

About to remove all Directory Server instances!
If this is not what you want, press ctrl-c now ...

5 ...
4 ...
3 ...
2 ...
1 ...
Removing instance: slapd-localhost
All instances have been successfully removed
DEBUG: The 389 Directory Server Creation Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: Called with: Namespace(verbose=True, json=False, file='/tmp/inst.inf', dryrun=False, func=<function instance_create at 0x7fe50038c5e0>)
DEBUG: Running setup with verbose
DEBUG: Using inf from /tmp/inst.inf
DEBUG: Configuration ['general', 'slapd', 'backend-userroot']
DEBUG: general:config_version not in inf, using default
DEBUG: general:full_machine_name not in inf, using default
DEBUG: general:strict_host_checking not in inf, using default
DEBUG: general:selinux not in inf, using default
DEBUG: general:systemd not in inf, using default
DEBUG: general:start not in inf, using default
DEBUG: general:defaults not in inf, using default
DEBUG: Configuration general {'config_version': 2, 'full_machine_name': 'localhost.localdomain', 'strict_host_checking': False, 'selinux': True, 'systemd': True, 'start': True, 'defaults': '999999999'}
DEBUG: slapd:user not in inf, using default
DEBUG: slapd:group not in inf, using default
DEBUG: slapd:root_dn not in inf, using default
DEBUG: slapd:prefix not in inf, using default
DEBUG: slapd:self_sign_cert not in inf, using default
DEBUG: slapd:self_sign_cert_valid_months not in inf, using default
DEBUG: slapd:bin_dir not in inf, using default
DEBUG: slapd:sbin_dir not in inf, using default
DEBUG: slapd:sysconf_dir not in inf, using default
DEBUG: slapd:initconfig_dir not in inf, using default
DEBUG: slapd:data_dir not in inf, using default
DEBUG: slapd:local_state_dir not in inf, using default
DEBUG: slapd:ldapi not in inf, using default
DEBUG: slapd:lib_dir not in inf, using default
DEBUG: slapd:cert_dir not in inf, using default
DEBUG: slapd:config_dir not in inf, using default
DEBUG: slapd:inst_dir not in inf, using default
DEBUG: slapd:backup_dir not in inf, using default
DEBUG: slapd:db_dir not in inf, using default
DEBUG: slapd:db_home_dir not in inf, using default
DEBUG: slapd:db_lib not in inf, using default
DEBUG: slapd:mdb_max_size not in inf, using default
DEBUG: slapd:ldif_dir not in inf, using default
DEBUG: slapd:lock_dir not in inf, using default
DEBUG: slapd:log_dir not in inf, using default
DEBUG: slapd:run_dir not in inf, using default
DEBUG: slapd:schema_dir not in inf, using default
DEBUG: slapd:tmp_dir not in inf, using default
DEBUG: Configuration slapd {'port': 389, 'group': 'dirsrv', 'self_sign_cert': True, 'self_sign_cert_valid_months': 24, 'secure_port': 636, 'user': 'dirsrv', 'instance_name': 'localhost', 'root_dn': 'cn=Directory Manager', 'root_password': 'password', 'initconfig_dir': '/etc/sysconfig', 'prefix': '/usr', 'bin_dir': '/usr/bin', 'sbin_dir': '/usr/sbin', 'sysconf_dir': '/etc', 'data_dir': '/usr/share', 'local_state_dir': '/var', 'lib_dir': '/usr/lib64', 'cert_dir': '/etc/dirsrv/slapd-localhost', 'config_dir': '/etc/dirsrv/slapd-localhost', 'inst_dir': '/usr/lib64/dirsrv/slapd-localhost', 'backup_dir': '/var/lib/dirsrv/slapd-localhost/bak', 'db_dir': '/var/lib/dirsrv/slapd-localhost/db', 'db_home_dir': '/dev/shm/slapd-localhost', 'db_lib': 'mdb', 'ldapi': '/run/slapd-localhost.socket', 'ldif_dir': '/var/lib/dirsrv/slapd-localhost/ldif', 'mdb_max_size': '10581403238.400002', 'lock_dir': '/run/lock/dirsrv/slapd-localhost', 'log_dir': '/var/log/dirsrv/slapd-localhost', 'run_dir': '/run/dirsrv', 'schema_dir': '/etc/dirsrv/slapd-localhost/schema', 'tmp_dir': '/tmp'}
DEBUG: backend-userroot:require_index not in inf, using default
DEBUG: backend-userroot:enable_replication not in inf, using default
DEBUG: backend-userroot:replica_role not in inf, using default
DEBUG: backend-userroot:replica_id not in inf, using default
DEBUG: backend-userroot:replica_binddn not in inf, using default
DEBUG: backend-userroot:replica_bindpw not in inf, using default
DEBUG: backend-userroot:replica_bindgroup not in inf, using default
DEBUG: backend-userroot:changelog_max_age not in inf, using default
DEBUG: backend-userroot:changelog_max_entries not in inf, using default
DEBUG: Configuration backends [{'name': 'userroot', 'suffix': 'dc=example,dc=com', 'create_suffix_entry': 'True', 'sample_entries': '999999999', 'enable_replication': False}]
DEBUG: START: Starting installation ...
DEBUG: READY: Preparing installation for localhost...
INFO: Validate installation settings ...
DEBUG: PASSED: using config settings 999999999
DEBUG: PASSED: user / group checking
DEBUG: PASSED: prefix checking
DEBUG: list() localhost instance not found: missing /etc/dirsrv/slapd-localhost/dse.ldif

DEBUG: PASSED: instance checking
DEBUG: INFO: temp root password set to doq7FMArFFtXvRKlokaaUmL5rtQVtuRf0vopspapWCjDkV6jU6L.k1evKJ0SIUsxl
DEBUG: PASSED: root user checking
DEBUG: PASSED: network avaliability checking
DEBUG: READY: Beginning installation for localhost...
DEBUG: ACTION: Creating dse.ldif
INFO: Create file system structures ...
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-localhost/bak
DEBUG: ACTION: creating /etc/dirsrv/slapd-localhost
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-localhost/db
DEBUG: ACTION: creating /dev/shm/slapd-localhost
DEBUG: ACTION: creating /var/lib/dirsrv/slapd-localhost/ldif
DEBUG: ACTION: creating /run/lock/dirsrv/slapd-localhost
DEBUG: ACTION: creating /var/log/dirsrv/slapd-localhost
DEBUG: ACTION: creating /run/dirsrv
DEBUG: b'CMD: systemctl enable dirsrv@localhost ; STDOUT:  ; STDERR: Created symlink /etc/systemd/system/multi-user.target.wants/dirsrv@localhost.service \xe2\x86\x92 /usr/lib/systemd/system/dirsrv@.service.\n'
DEBUG: ACTION: Creating certificate database is /etc/dirsrv/slapd-localhost
DEBUG: Allocate <class 'lib389.DirSrv'> with None
DEBUG: Allocate <class 'lib389.DirSrv'> with /run/slapd-localhost.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with localhost:389
DEBUG: Allocate <class 'lib389.DirSrv'> with localhost:389
DEBUG: nss cmd: /usr/bin/certutil -N -d /etc/dirsrv/slapd-localhost -f /etc/dirsrv/slapd-localhost/pwdfile.txt -@ /etc/dirsrv/slapd-localhost/pwdfile.txt
DEBUG: nss output:
INFO: Create self-signed certificate database ...
DEBUG: nss cmd: /usr/bin/certutil -N -d /etc/dirsrv/ssca/ -f /etc/dirsrv/ssca//pwdfile.txt -@ /etc/dirsrv/ssca//pwdfile.txt
DEBUG: nss output:
DEBUG: nss cmd: /usr/bin/certutil -S -n Self-Signed-CA -s CN=ssca.389ds.example.com,O=testing,L=389ds,ST=Queensland,C=AU -x -g 4096 -t CT,, -v 24 -2 --keyUsage certSigning -d /etc/dirsrv/ssca/ -z /etc/dirsrv/ssca//noise.txt -f /etc/dirsrv/ssca//pwdfile.txt
DEBUG: nss output: Is this a CA certificate [y/N]?
Enter the path length constraint, enter to skip [<0 for unlimited path]: > Is this a critical extension [y/N]?

DEBUG: nss cmd: /usr/bin/certutil -L -n Self-Signed-CA -d /etc/dirsrv/ssca/ -a
DEBUG: nss cmd: /usr/bin/openssl rehash /etc/dirsrv/ssca/
DEBUG: CSR name -> None
DEBUG: CSR subject -> CN=localhost.localdomain,givenName=22be61ea-a3f3-4852-af0b-749c0dc8f347,O=testing,L=389ds,ST=Queensland,C=AU
DEBUG: CSR alt_names -> ['localhost.localdomain']
DEBUG: nss cmd: /usr/bin/certutil -R --keyUsage digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment --nsCertType sslClient,sslServer --extKeyUsage clientAuth,serverAuth -s CN=localhost.localdomain,givenName=22be61ea-a3f3-4852-af0b-749c0dc8f347,O=testing,L=389ds,ST=Queensland,C=AU -8 localhost.localdomain -g 4096 -d /etc/dirsrv/slapd-localhost -z /etc/dirsrv/slapd-localhost/noise.txt -f /etc/dirsrv/slapd-localhost/pwdfile.txt -a -o /etc/dirsrv/slapd-localhost/Server-Cert.csr
DEBUG: nss cmd: /usr/bin/certutil -C -d /etc/dirsrv/ssca/ -f /etc/dirsrv/ssca//pwdfile.txt -v 24 -a -i /etc/dirsrv/slapd-localhost/Server-Cert.csr -o /etc/dirsrv/slapd-localhost/Server-Cert.crt -c Self-Signed-CA
DEBUG: nss cmd: /usr/bin/openssl rehash /etc/dirsrv/slapd-localhost
DEBUG: nss cmd: /usr/bin/certutil -A -n Self-Signed-CA -t CT,, -a -i /etc/dirsrv/slapd-localhost/ca.crt -d /etc/dirsrv/slapd-localhost -f /etc/dirsrv/slapd-localhost/pwdfile.txt
DEBUG: nss cmd: /usr/bin/certutil -A -n Server-Cert -t ,, -a -i /etc/dirsrv/slapd-localhost/Server-Cert.crt -d /etc/dirsrv/slapd-localhost -f /etc/dirsrv/slapd-localhost/pwdfile.txt
DEBUG: nss cmd: /usr/bin/certutil -V -d /etc/dirsrv/slapd-localhost -n Server-Cert -u YCV
DEBUG: port 636 already in [389, 636, 3268, 3269, 7389], skipping port relabel
INFO: Perform SELinux labeling ...
DEBUG: port 389 already in [389, 636, 3268, 3269, 7389], skipping port relabel
DEBUG: asan_enabled=False
DEBUG: libfaketime installed =False
DEBUG: systemd status -> True
DEBUG: systemd status -> True
INFO: Cannot find the error log file /var/log/dirsrv/slapd-localhost/errors.
INFO: Failed to start dirsrv@localhost: "Job for dirsrv@localhost.service failed because the control process exited with error code.
See "systemctl status dirsrv@localhost.service" and "journalctl -xeu dirsrv@localhost.service" for details.
"
INFO: Command '['systemctl', 'start', 'dirsrv@localhost']' returned non-zero exit status 1.
DEBUG: Command '['systemctl', 'start', 'dirsrv@localhost']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/sbin/dscreate", line 99, in <module>
    result = args.func(inst, log, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lib389/cli_ctl/instance.py", line 72, in instance_create
    if sd.create_from_inf(args.file):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lib389/instance/setup.py", line 596, in create_from_inf
    self.create_from_args(general, slapd, backends, self.extra)
  File "/usr/lib/python3.12/site-packages/lib389/instance/setup.py", line 758, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.12/site-packages/lib389/instance/setup.py", line 1037, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.12/site-packages/lib389/__init__.py", line 1117, in start
    raise e from None
  File "/usr/lib/python3.12/site-packages/lib389/__init__.py", line 1112, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemctl', 'start', 'dirsrv@localhost']' returned non-zero exit status 1.
ERROR: Error: Command '['systemctl', 'start', 'dirsrv@localhost']' returned non-zero exit status 1.
```
Logs:
```
Wed 2024-06-05 05:13:14 EDT systemd[1]: Starting dirsrv@localhost.service - 389 Directory Server localhost....
░░ Subject: A start job for unit dirsrv@localhost.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit dirsrv@localhost.service has begun execution.
░░
░░ The job identifier is 5217.
Wed 2024-06-05 05:13:14 EDT ns-slapd[61722]: [05/Jun/2024:05:13:14.191982310 -0400] - INFO - dse_check_file - The config /etc/dirsrv/slapd-localhost/dse.ldif can not be accessed. Attempting restore ... (reason: 0)
Wed 2024-06-05 05:13:14 EDT ns-slapd[61722]: [05/Jun/2024:05:13:14.192044337 -0400] - INFO - dse_check_file - The backup /etc/dirsrv/slapd-localhost/dse.ldif.bak can not be accessed. Check it exists and permissions.
Wed 2024-06-05 05:13:14 EDT ns-slapd[61722]: [05/Jun/2024:05:13:14.192049858 -0400] - ERR - slapd_bootstrap_config - No valid configurations can be accessed! You must restore /etc/dirsrv/slapd-localhost/dse.ldif from backup!
Wed 2024-06-05 05:13:14 EDT ns-slapd[61722]: [05/Jun/2024:05:13:14.192052273 -0400] - EMERG - main - The configuration files in directory /etc/dirsrv/slapd-localhost could not be read or were not found.  Please refer to the error log or output for more information.
Wed 2024-06-05 05:13:14 EDT systemd[1]: dirsrv@localhost.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStart= process belonging to unit dirsrv@localhost.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Wed 2024-06-05 05:13:14 EDT systemd[1]: dirsrv@localhost.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit dirsrv@localhost.service has entered the 'failed' state with result 'exit-code'.
Wed 2024-06-05 05:13:14 EDT systemd[1]: Failed to start dirsrv@localhost.service - 389 Directory Server localhost..
░░ Subject: A start job for unit dirsrv@localhost.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit dirsrv@localhost.service has finished with a failure.
░░
░░ The job identifier is 5217 and the job result is failed.
```

**Comment by vashirov** [comment]
It fails only when `CapabilityBoundingSet=CAP_NET_BIND_SERVICE` is set in the systemd service. If I comment it out, the instance creation works, service starts.

**Comment by Firstyear** [comment]
That's a pretty scary set of capabilities though, especially DAC_OVERRIDE. 

```
       CAP_DAC_OVERRIDE
              Bypass file read, write, and execute permission checks.
              (DAC is an abbreviation of "discretionary access
              control".)
```

Even setuid/setgid as caps are pretty scary. Are we sure we want to be enabling these?

**Comment by Firstyear** [comment]
Right, I think @vashirov is correct (as always :) ) 

CapabilityBoundingSet is the allowed set of capabilities. Ambient is what is implicitly granted. When starting as non-root, the process can't grant itself CAP_DAC/SETGID/SETUID because it lacks SETPCAP. When running as root, root is allowed those capabilities and then drops them during setuid/setgid (as I am reading it).

https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#CapabilityBoundingSet=

https://man7.org/linux/man-pages/man7/capabilities.7.html

So I think we expand the bounding set as vashirov suggests, but leave ambient as net-bind only. Does this seem reasonable? Or am I missing something in how capabilities work here?

**Comment by vashirov** [comment]
Sorry if I wasn't clear, what I meant was that before this change the service had all kinds of scary capabilities:
```
# systemd-analyze security dirsrv@localhost | grep CAP
✓ CapabilityBoundingSet=~CAP_SYS_TIME                         Service processes cannot change the system clock
✗ CapabilityBoundingSet=~CAP_SYS_PACCT                        Service may use acct()                                                       0.1
✗ CapabilityBoundingSet=~CAP_KILL                             Service may send UNIX signals to arbitrary processes                         0.1
✗ CapabilityBoundingSet=~CAP_(DAC_*|FOWNER|IPC_OWNER)         Service may override UNIX file/IPC permission checks                         0.2
✗ CapabilityBoundingSet=~CAP_BPF                              Service may not load BPF programs                                            0.1
✗ CapabilityBoundingSet=~CAP_LINUX_IMMUTABLE                  Service may mark files immutable                                             0.1
✗ CapabilityBoundingSet=~CAP_IPC_LOCK                         Service may lock memory into RAM                                             0.1
✗ CapabilityBoundingSet=~CAP_SYS_TTY_CONFIG                   Service may issue vhangup()                                                  0.1
✗ CapabilityBoundingSet=~CAP_SYS_BOOT                         Service may issue reboot()                                                   0.1
✗ CapabilityBoundingSet=~CAP_SYS_CHROOT                       Service may issue chroot()                                                   0.1
✗ CapabilityBoundingSet=~CAP_BLOCK_SUSPEND                    Service may establish wake locks                                             0.1
✗ CapabilityBoundingSet=~CAP_LEASE                            Service may create file leases                                               0.1
✗ CapabilityBoundingSet=~CAP_(CHOWN|FSETID|SETFCAP)           Service may change file ownership/access mode/capabilities unrestricted      0.2
✗ CapabilityBoundingSet=~CAP_SET(UID|GID|PCAP)                Service may change UID/GID identities/capabilities                           0.3
✗ CapabilityBoundingSet=~CAP_MAC_*                            Service may adjust SMACK MAC                                                 0.1
✗ CapabilityBoundingSet=~CAP_SYS_PTRACE                       Service has ptrace() debugging abilities                                     0.3
✗ CapabilityBoundingSet=~CAP_SYS_(NICE|RESOURCE)              Service has privileges to change resource use parameters                     0.1
✓ CapabilityBoundingSet=~CAP_SYS_RAWIO                        Service has no raw I/O access
✓ CapabilityBoundingSet=~CAP_SYSLOG                           Service has no access to kernel logging
✗ CapabilityBoundingSet=~CAP_NET_ADMIN                        Service has network configuration privileges                                 0.2
✗ CapabilityBoundingSet=~CAP_NET_(BIND_SERVICE|BROADCAST|RAW) Service has elevated networking privileges                                   0.1
✗ CapabilityBoundingSet=~CAP_AUDIT_*                          Service has audit subsystem access                                           0.1
✗ CapabilityBoundingSet=~CAP_SYS_ADMIN                        Service has administrator privileges                                         0.3
✓ CapabilityBoundingSet=~CAP_WAKE_ALARM                       Service cannot program timers that wake up the system
✓ CapabilityBoundingSet=~CAP_SYS_MODULE                       Service cannot load kernel modules
✓ CapabilityBoundingSet=~CAP_MKNOD                            Service cannot create device nodes
```

```
# capsh --decode=$(grep CapBnd /proc/$(pgrep ns-slapd)/status | awk '{print $2}')
0x000001f3f5fcffff=cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap
_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys
_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_block_su
spend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
```

```
# grep Cap /proc/$(pgrep ns-slapd)/status
CapInh: 0000000000000000
CapPrm: 0000000000000000
CapEff: 0000000000000000
CapBnd: 000001f3f5fcffff
CapAmb: 0000000000000000
```

This is what `capable` from bcc-tools reports when I start/restart the server:
```
# /usr/share/bcc/tools/capable | grep ns-slapd | awk '{print $6}' > ns-slapd.caps
^C
# sort -u ns-slapd.caps
CAP_DAC_OVERRIDE
CAP_DAC_READ_SEARCH
CAP_MKNOD
CAP_NET_ADMIN
CAP_NET_BIND_SERVICE
CAP_SETGID
CAP_SETPCAP
CAP_SETUID
CAP_SYS_ADMIN
CAP_SYS_RESOURCE
```

I absolutely agree with you on removing the unnecessary capabilities.
But the current problem is that with `CapabilityBoundingSet=CAP_NET_BIND_SERVICE` service doesn't start at all. So we either need to extend the Bounding set _as a workaround_ to unbreak the `main` branch, or change the code to not require setuid/setgid, if possible (I suspect that https://github.com/389ds/389-ds-base/blob/bb887aa435c8e647dc94a70b808a98a5319293bb/ldap/servers/slapd/main.c#L239 is responsible).

**Comment by Firstyear** [comment]
Yeah I agree with you :) I think the suggestion I proposed will fix it for you and also limits what can be done nicely.
