### ISSUE TITLE
Crash during online import (assertion failure)

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6195]
**Issue Description**

Export a replicated database to ldif and do an online import causes an assertion failure/crash:

```
# dsconf slapd-localhost backend export userroot -l db.ldif --replication 

# dsconf slapd-localhost backend import userroot -l db.ldif  

(gdb) where
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fb98ee8a8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fb98ee388ee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fb98ee208ff in __GI_abort () at abort.c:79
#4  0x00007fb98e9d56b6 in PR_Assert (s=0x7fb98a398f6d "fi->entry->ep_refcnt > 0", file=0x7fb98a3ac6e0 "../389-ds-base/ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c", ln=168)
    at ../../../../nspr/pr/src/io/prlog.c:571
#5  0x00007fb98a37eb4d in bdb_import_fifo_fetch (job=0x7fb910a8d000, id=1, worker=1) at ../389-ds-base/ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:168
#6  0x00007fb98a38db31 in bdb_import_worker (param=0x7fb919e18280) at ../389-ds-base/ldap/servers/slapd/back-ldbm/db-bdb/bdb_import_threads.c:2897
#7  0x00007fb98e9f0749 in _pt_root (arg=0x7fb919e303c0) at ../../../../nspr/pr/src/pthreads/ptthread.c:201
#8  0x00007fb98ee88897 in start_thread (arg=<optimized out>) at pthread_create.c:444
#9  0x00007fb98ef0fa5c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

(gdb) p fi->entry->ep_refcnt
$1 = 0
(gdb) p *fi->entry
$3 = {ep_type = 0, ep_lrunext = 0x0, ep_lruprev = 0x0, ep_id = 513, ep_state = 4 '\004', ep_refcnt = 0, ep_size = 0, ep_create_time = {tv_sec = 0, tv_nsec = 0}, 
  ep_entry = 0x7fb8fb83a000, ep_vlventry = 0x0, ep_dn_link = 0x0, ep_id_link = 0x0, ep_uuid_link = 0x0, ep_mutexp = 0x0}

(gdb) p *fi->entry->ep_entry
$4 = {e_sdn = {flag = 6 '\006', udn = 0x0, dn = 0x7fb8fb82d3b0 "uid=testuser00498,dc=example,dc=com", ndn = 0x7fb8fbe3b7d0 "uid=testuser00498,dc=example,dc=com", 
    ndn_len = 35}, e_srdn = {flag = 0 '\000', rdn = 0x7fb8fbe490a0 "uid=testuser00498", rdns = 0x0, butcheredupto = -1, nrdn = 0x0, all_rdns = 0x7fb8fbe49080, 
    all_nrdns = 0x0}, e_uniqueid = 0x7fb8fbe3b860 "aef878f2-063f11ef-8758ed60-9f590b57", e_dncsnset = 0x7fb8fb884400, e_maxcsn = 0x7fb8fb883700, e_attrs = 0x7fb8fb87f1a0, 
  e_deleted_attrs = 0x7fb8fb8851e0, e_virtual_attrs = 0x0, e_virtual_watermark = 0, e_virtual_lock = 0x7fb8fb870880, e_extension = 0x7fb8fb883730, e_flags = 0 '\000', 
  e_aux_attrs = 0x0}



# entry-id: 514
dn: uid=testuser00498,dc=example,dc=com
modifyTimestamp;adcsn-665732f4004000010002;vucsn-665732f4004000010002: 2024052
 9135148Z
modifiersName;adcsn-665732f4004000010001;vucsn-665732f4004000010001: cn=Member
 Of Plugin,cn=plugins,cn=config
nsUniqueId: aef878f2-063f11ef-8758ed60-9f590b57
objectClass;vucsn-662fc119000900010000: top
objectClass;vucsn-662fc119000900010000: person
objectClass;vucsn-662fc119000900010000: inetorgperson
objectClass;vucsn-662fc119000900010000: organizationalPerson
objectClass;vucsn-662fc119000900010000: inetUser
uid;vucsn-662fc119000900010000;mdcsn-662fc119000900010000: testuser00498
cn;vucsn-662fc119000900010000: iXQazKusti SMXtqRVVterlqknirHREoauGBu
sn;vucsn-662fc119000900010000: SMXtqRVVterlqknirHREoauGBu
givenName;vucsn-662fc119000900010000: iXQazKusti
description;vucsn-662fc119000900010000: Description for testuser
homePhone;vucsn-662fc119000900010000: +1 408 617-1388
initials;vucsn-662fc119000900010000: te
telephoneNumber;vucsn-662fc119000900010000: +1 303 379-9926
facsimileTelephoneNumber;vucsn-662fc119000900010000: +1 650 711-2093
mobile;vucsn-662fc119000900010000: +1 415 694-6787
pager;vucsn-662fc119000900010000: +1 213 395-6178
manager;vucsn-662fc119000900010000: uid=DReynolds,dc=example,dc=com
secretary;vucsn-662fc119000900010000: cn=Diana Key,dc=example,dc=com
roomNumber;vucsn-662fc119000900010000: 47186
carLicense;vucsn-662fc119000900010000: nlGTJC
l;vucsn-662fc119000900010000: Santa Clara
mail;vucsn-662fc119000900010000: testuser00498@example.com
userCertificate;binary;vucsn-662fc119000900010000:: MIIBvjCCASegAwIBAgIBAjANBg
 kqhkiG9w0BAQQFADAnMQ8wDQYDVQQDEwZjb25maWcxFDASBgNVBAMTC01NUiBDQSBDZXJ0MB4XDTA
 xMDQwNTE1NTEwNloXDTExMDcwNTE1NTEwNlowIzELMAkGA1UEChMCZnIxFDASBgNVBAMTC01NUiBT
 MSBDZXJ0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNlmsKEaPD+o3mAUwmW4E40MPs7aiui
 1YhorST3KzVngMqe5PbObUHMeJN7CLbq9SjXvdB3y2AoVl/s5UkgGz8krmJ8ELfUCU95AQls321Rw
 BdLRjioiQ3MGJiFjxwYRIVj1CUTuX1y8dC7BWvZ1/EB0yv0QDtp2oVMUeoK9/9sQIDAQABMA0GCSq
 GSIb3DQEBBAUAA4GBADevhxY6QyDMK3Mnr7vLGe/HWEZCObF+qEo2zWScGH0Q+dAmhkCCkNeHJoqG
 N4NWjTdnBcGaAr5Y85k1o/vOAMBsZePbYx4SrywL0b/OkOmQX+mQwieC2IQzvaBRyaNMh309vrF4w
 5kExReKfjR/gXpHiWQzGSxC5LeQG4k3IP34
creatorsName;vucsn-662fc119000900010000: cn=dm
createTimestamp;vucsn-662fc119000900010000: 20240429154737Z
entryUUID: a22daad1-134a-4aea-b7c6-d09fd387bcbe
dsEntryDN: uid=testuser00498,dc=example,dc=com
memberOf;adcsn-665732f4004000010000;vdcsn-665732f4004000010000;deletedattribute;deleted:
```

**Comment by mreynolds389** [comment]
The crash only occurs if the cachesize is set very low:

dn: cn=userroot,cn=ldbm database,cn=plugins,cn=config
nsslapd-cachesize: 512

**Comment by tbordaz** [comment]
Worth a try to reproduce (replicated) and checking if fifo import was containing a fix around that area. In a first try @droideck was not able to reproduce.
