### ISSUE TITLE
AddressSanitizer: SEGV in PR_CloseDir

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#6251]
**Issue Description**
```
=================================================================
==27749==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7f7022d19240 bp 0x7f6c8d5ff540 sp 0x7f6c8d5ff390 T27)
==27749==The signal is caused by a READ memory access.
==27749==Hint: address points to the zero page.
    #0 0x7f7022d19240 in PR_CloseDir (/lib64/libnspr4.so+0x28240) (BuildId: 550873063529004969f2e1d67074edc23c9960ab)
    #1 0x7f701b628c36 in ldbm_archive_config (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0x28c36) (BuildId: 9600140bf69e2d59448220607c7787cc186856c4)
    #2 0x7f701b73fee4 in dbmdb_backup ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:982
    #3 0x7f701b63e2d2 in ldbm_back_ldbm2archive ldap/servers/slapd/back-ldbm/archive.c:423
    #4 0x7f702271dc73 in task_backup_thread ldap/servers/slapd/task.c:1501
    #5 0x7f7022d1aae0 in _pt_root ../../../../nspr/pr/src/pthreads/ptthread.c:201
    #6 0x7f7022e5e359 in asan_thread_start ../../../../libsanitizer/asan/asan_interceptors.cpp:234
    #7 0x7f70222bd811 in start_thread /usr/src/debug/glibc-2.39-16.el10.x86_64/nptl/pthread_create.c:447
    #8 0x7f702232d27b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libnspr4.so+0x28240) (BuildId: 550873063529004969f2e1d67074edc23c9960ab) in PR_CloseDir
Thread T27 created by T12 here:
    #0 0x7f7022ef4119 in pthread_create (/lib64/libasan.so.8+0xf4119) (BuildId: 312d4453e0ef390e02032b63e996e2d9e4ced2fb)
    #1 0x7f7022d1a7dd in _PR_CreateThread ../../../../nspr/pr/src/pthreads/ptthread.c:458

Thread T12 created by T0 here:
    #0 0x7f7022ef4119 in pthread_create (/lib64/libasan.so.8+0xf4119) (BuildId: 312d4453e0ef390e02032b63e996e2d9e4ced2fb)
    #1 0x7f7022d1a7dd in _PR_CreateThread ../../../../nspr/pr/src/pthreads/ptthread.c:458

==27749==ABORTING
```
**Package Version and Platform:**
389-ds-base-3.0.3-9.asan.el10.x86_64

**Steps to Reproduce**
dirsrvtests/tests/suites/backups/backup_test.py::test_backup_task_after_failure

```
------------------------------------------------ Extract of instance standalone1 error log -------------------------------------------------
[04/Jul/2024:15:41:49.249901661 -0400] - ERR - dbmdb_copyfile - Failed to open dest file /var/lib/dirsrv/slapd-standalone1/bak/bak1/INFO.mdb by "No such file or directory"
[04/Jul/2024:15:41:49.253101840 -0400] - ERR - dbmdb_backup - Error in copying version file (/var/lib/dirsrv/slapd-standalone1/db/INFO.mdb -> /var/lib/dirsrv/slapd-standalone1/bak/bak1/INFO.mdb): err=-1
[04/Jul/2024:15:41:49.270801317 -0400] - ERR - ldbm_archive_config - Failed to create directory /var/lib/dirsrv/slapd-standalone1/bak/bak1/config_files - Error 2
-------------------------------------------------- Database info for instance standalone1 --------------------------------------------------
```

**Comment by progier389** [comment]
We should double check ldap/servers/slapd/back-ldbm/archive.c in the build sources but 
IMHO crash in PR_CloseDir after failed open means that the code is not:
```
    725 error:
    726     if (NULL != dirhandle) {
    727         PR_CloseDir(dirhandle);
    728         dirhandle = NULL;
    729     }
```
As it should be after recent PR  #6230
So maybe you are running the test case of a fix that is not yet integrated in that version.
