### ISSUE TITLE
UI - Enabling replication for a sub suffix crashes browser

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#6254]
Description of problem:
Web Console: Enabling replication for a sub suffix causes `TypeError: this.props.data.nsds5replicabinddn is not iterable`

How reproducible:
Always

Steps to Reproduce:
1. Create a sub suffix
dsconf ... backend create --suffix="ou=people,dc=example,dc=com" --be-name="people" --parent-suffix="dc=example,dc=com"

2. Enable Replication from Web Console

https://example.com:9090/389-console
Replication -> Suffixes -> ou=people,dc=example,dc=com
[Enable Replication]
Set only Password

3. Select Replication -> Suffixes -> ou=people,dc=example,dc=com

4. Get Ooops!

```
TypeError: this.props.data.nsds5replicabinddn is not iterable
    at J5.render (index.js:647:180733)
    at yk (index.js:5:65571)
    at mU (index.js:5:65368)
    at aq (index.js:9:9718)
    at QW (index.js:9:952)
    at E5e (index.js:9:878)
    at a7 (index.js:9:729)
    at Lk (index.js:7:10840)
    at index.js:5:38845
    at ls.unstable_runWithPriority (index.js:1:11969)
Sk	@	index.js:7
```

Actual results:
Get Ooops!

Expected results:
Don't get Ooops!

**Comment by droideck** [comment]
7cb34ed42..5dca4f0e7  389-ds-base-2.5 -> 389-ds-base-2.5
   cc723ef46..61ae3ef08  389-ds-base-2.4 -> 389-ds-base-2.4
   47672fb37..a9c80e93e  389-ds-base-2.3 -> 389-ds-base-2.3
   560b13273..d24321e77  389-ds-base-2.2 -> 389-ds-base-2.2
   2008bb754..96a669f57  389-ds-base-2.1 -> 389-ds-base-2.1
   96b19fd69..1e955a146  389-ds-base-2.0 -> 389-ds-base-2.0
   b8dbffaf8..e73ee38c6  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
