### ISSUE TITLE
dsconf backup create hangs on a container created with 389ds/dirsrv:3.1 docker image

### ISSUE THREAD

**Issue by mayurcrunchr** [389ds/389-ds-base#6372]
**Issue Description**

We have a cronjob that runs the following command to backup the ldap database online every hour at `55 minutes( 55 * * * *) `
`"docker exec -i ldap dsconf -D "cn=Directory Manager" localhost backup create /tmp/ansible.1bu66l05/db"`

The job takes backup successfuly and finishes successfully for few hours(23 hours in this case) and then hangs suddenly while copying backup files (after 24 iterations or 24 hours in this case)

` "[20/Oct/2024:22:55:33.029998779 +0000] - INFO - archive_copyfile - Copying /etc/dirsrv/slapd-localhost/slapd-collations.conf to /tmp/ansible.1bu66l05/db/config_files/slapd-collations.conf"`

We are using the docker image 389ds/dirsrv:3.1 on a Ubuntu 20.04.6 LTS host

**Package Version and Platform:**
 - Platform: openSUSE Tumbleweed , release: 20240726
 - Package and version: [389-ds  3.1.1~git0.aef1668-180.1 x86_64]

**Steps to Reproduce**
1. Create a ldap docker container using docker image 389ds/dirsrv:3.1 on a ubuntu 20.04.6 LTS host
2. Add a backend and set the nsslapd-backend-implement to bdb(we have also observed the same problem on fresh mdb database)
3. Create a test group 
4. Create a test user and add the test user to the test group created in step 3
5. Enable the cronjob  to backup the ldap db every hour at 55 minutes
`55 * * * * docker exec -i ldap dsconf -D "cn=Directory Manager" localhost backup create /tmp/ansible.1bu66l05/db`
6. After few hours(24 hours in our case), the dsconf backup hangs

**Screenshots**
![image](https://github.com/user-attachments/assets/274bce93-8eb0-4ac3-8fef-f543d7cede0f)
![image](https://github.com/user-attachments/assets/14979091-a08c-47fd-b6ab-a2e9b22823d5)
![image](https://github.com/user-attachments/assets/b6c0084c-7a64-4f86-ba5e-89f5e98476d2)

**Additional context**
Please find attached the backend config, nsslapd config params, access logs, error logs, db_stat output, gdb backtrace for ns-slapd, dsconf and dscontainer processes.

[389ds-3.1-debug-files-all.tar.gz](https://github.com/user-attachments/files/17458832/389ds-3.1-debug-files-all.tar.gz)

 GDB outputs has been taken using the command described in https://www.port389.org/docs/389ds/FAQ/faq.html

We did try running the command `docker exec -i ldap dsconf -D "cn=Directory Manager" localhost backup create /tmp/ansible.1bu66l05/db" `in a for loop 140 times, and were not able to repro the issue using this method.

FYI: We also have a health check service running on the host that does the following every 30 seconds
`"/usr/bin/ldapwhoami ldapsearch -H ldap://127.0.0.1:3389 -x -D 'cn=Directory Manager' -y /etc/ldap_password"`

We did not encounter this problem with 389ds/dirsrv:2.4

**Comment by mayurcrunchr** [comment]
Just another bits of information: 
We did try running the command  docker exec -i ldap dsconf -D "cn=Directory Manager" localhost backup create /tmp/ansible.1bu66l05/db" in a for loop 140 times, and were not able to repro the issue using this method.

FYI:  We also have a health check service running on the host that does
"/usr/bin/ldapwhoami  ldapsearch -H ldap://127.0.0.1:3389 -x -D 'cn=Directory Manager' -y /etc/ldap_password"

**Comment by mayurcrunchr** [comment]
we were also able to repro this issue using a fresh mdb database(default settings) with docker image 389ds/dirsrv:3.1 using the latest 389ds base package. This stacktrace has the debug symbols and contain more verbose information about the variables

![image](https://github.com/user-attachments/assets/80256a46-5c95-4248-b34a-ee4f1f5538ad)
[mdb_dsconf_hang_stacktrace.tar.gz](https://github.com/user-attachments/files/17553545/mdb_dsconf_hang_stacktrace.tar.gz)

**Comment by mayurcrunchr** [comment]
> > The job takes backup successfuly and finishes successfully for few hours(23 hours in this case) and then hangs suddenly while copying backup files (after 24 iterations or 24 hours in this case)
> 
> Does this happen every time after 24h? Do you have enough space on the host system?
It's inconsistent. With bdb database it happened after 24 hours but not on all our servers. With mdb database, it happened after 8 days.

We have plenty of space I think around 11Gb spare
![image](https://github.com/user-attachments/assets/102fecca-0cc6-465f-99b5-c84f460a5b38)

> 
> > /tmp/ansible.1bu66l05/db
> 
> Is there a reason you're not creating backups in the default location in /data? Usually /data is mounted as a persistent volume, containing all configuration, database, ldifs and backups.
we didn't want to pollute the /data directory in case the backup terminated unsuccessfully. we first copy it to a tmp folder and only when the backup command runs successfully we copy it over to the /data directory

**Comment by vashirov** [comment]
Ok, I reproduced the issue on a fresh instance by running in parallel:
```
while :; do dsconf localhost backup create; done
```
After about 74 iterations it hanged.

**Comment by vashirov** [comment]
I found a faster reproducer. The deadlock happens when I continuously modify `cn=config` and then start the backup task. The server hangs immediately. 
I.e. run this in one terminal
```
while :
        do ldapmodify -D cn=Directory\ Manager -w password << EOF
dn: cn=config
changetype: modify
replace: nsslapd-versionstring
nsslapd-versionstring: 389-Directory/3.1.1
-

EOF
done
```

and then start the backup task in another:
```
dsconf localhost backup create
```

There are 3 competing threads:
```
Thread 2 (Thread 0x7fa2fa0006c0 (LWP 7278) "ns-slapd"):
#0  0x00007fa67447ae0b in __futex_abstimed_wait_common () at target:/lib64/libc.so.6
#1  0x00007fa6744843da in pthread_rwlock_rdlock@GLIBC_2.2.5 () at target:/lib64/libc.so.6
#2  0x00007fa674629f0a in slapi_rwlock_rdlock (rwlock=<optimized out>) at ldap/servers/slapd/slapi2runtime.c:288
#3  dse_get_entry_copy (pdse=0x7fa67302dc20, dn=0x7fa305784380, use_lock=<optimized out>) at ldap/servers/slapd/dse.c:196
#4  0x00007fa6746321ba in dse_modify (pb=0x7fa672a2a4a0) at ldap/servers/slapd/dse.c:1873
#5  0x00007fa674667360 in op_shared_modify (pb=0x7fa672a2a4a0, pw_change=0, old_pw=0x0) at ldap/servers/slapd/modify.c:1026
#6  0x00007fa6746ccc6c in modify_internal_pb.isra.0 (pb=pb@entry=0x7fa672a2a4a0) at ldap/servers/slapd/modify.c:572
#7  0x00007fa674665f46 in slapi_modify_internal_pb (pb=0x7fa672a2a4a0) at ldap/servers/slapd/modify.c:442
#8  0x00007fa6746b34ec in modify_internal_entry (dn=0x7fa6731e9610 "cn=backup_2024-10-29t13:13:39.654809,cn=backup,cn=tasks,cn=config", mods=0x7fa2f9ffe950) at ldap/servers/slapd/task.c:772
#9  slapi_task_status_changed (task=0x7fa66fb04f80) at ldap/servers/slapd/task.c:363
#10 0x00007fa6746b37f5 in slapi_task_status_changed (task=task@entry=0x7fa66fb04f80) at ldap/servers/slapd/task.c:392
#11 0x00007fa6746b4343 in slapi_task_log_notice (task=task@entry=0x7fa66fb04f80, format=format@entry=0x7fa6700b1848 "archive_copyfile - Copying %s to %s") at ldap/servers/slapd/task.c:322
#12 0x00007fa66ffcdea3 in archive_copyfile (source=0x7fa3057b69f0 "/etc/dirsrv/slapd-localhost/schema/99user.ldif", destination=0x7fa3057cfa00 "/var/lib/dirsrv/slapd-localhost/bak/localhost-2024-10-29T13:13:39.649749/config_files/schema", filename=filename@entry=0x7fa305969e83 "99user.ldif", mode=mode@entry=420, task=task@entry=0x7fa66fb04f80) at ldap/servers/slapd/back-ldbm/archive.c:552
#13 0x00007fa66ffce8c2 in ldbm_archive_config (bakdir=<optimized out>, task=0x7fa66fb04f80) at ldap/servers/slapd/back-ldbm/archive.c:697
#14 0x00007fa67004cc5b in dbmdb_backup (li=0x7fa6728bd080, dest_dir=0x7fa3057b5370 "/var/lib/dirsrv/slapd-localhost/bak/localhost-2024-10-29T13:13:39.649749", task=0x7fa66fb04f80) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:982
#15 0x00007fa66ffd5592 in ldbm_back_ldbm2archive (pb=<optimized out>) at ldap/servers/slapd/back-ldbm/archive.c:411
#16 0x00007fa6746b499b in task_backup_thread (arg=0x7fa672a2a6e0) at ldap/servers/slapd/task.c:1501
#17 0x00007fa673de13b7 in _pt_root () at target:/lib64/libnspr4.so
#18 0x00007fa67447e797 in start_thread () at target:/lib64/libc.so.6
#19 0x00007fa67450278c in __clone3 () at target:/lib64/libc.so.6


Thread 11 (Thread 0x7fa2ffa006c0 (LWP 6900) "ns-slapd"):
#0  0x00007fa67447b0c0 in __lll_lock_wait () at target:/lib64/libc.so.6
#1  0x00007fa674481f31 in pthread_mutex_lock@@GLIBC_2.2.5 () at target:/lib64/libc.so.6
#2  0x00007fa673dda175 in PR_Lock () at target:/lib64/libnspr4.so
#3  0x00007fa6746ce0a3 in dse_write_file_nolock.part.0.isra.0 (pdse=0x7fa67302dc20) at ldap/servers/slapd/dse.c:976
#4  0x00007fa674632796 in dse_write_file_nolock (pdse=0x7fa67302dc20) at ldap/servers/slapd/dse.c:969
#5  dse_replace_entry (pdse=0x7fa67302dc20, e=0x7fa3057a23c0, write_file=<optimized out>, use_lock=1) at ldap/servers/slapd/dse.c:1306
#6  dse_modify (pb=0x7fa3056fe760) at ldap/servers/slapd/dse.c:2069
#7  0x00007fa674667360 in op_shared_modify (pb=pb@entry=0x7fa3056fe760, pw_change=pw_change@entry=0, old_pw=0x0) at ldap/servers/slapd/modify.c:1026
#8  0x00007fa67466910e in do_modify (pb=pb@entry=0x7fa3056fe760) at ldap/servers/slapd/modify.c:377
#9  0x00005563a2ddb8bb in connection_dispatch_operation (conn=<optimized out>, op=<optimized out>, pb=<optimized out>) at ldap/servers/slapd/connection.c:654
#10 connection_threadmain (arg=<optimized out>) at ldap/servers/slapd/connection.c:1921
#11 0x00007fa673de13b7 in _pt_root () at target:/lib64/libnspr4.so
#12 0x00007fa67447e797 in start_thread () at target:/lib64/libc.so.6
#13 0x00007fa67450278c in __clone3 () at target:/lib64/libc.so.6


Thread 14 (Thread 0x7fa3018006c0 (LWP 6897) "ns-slapd"):
#0  0x00007fa67447ae0b in __futex_abstimed_wait_common () at target:/lib64/libc.so.6
#1  0x00007fa6744843da in pthread_rwlock_rdlock@GLIBC_2.2.5 () at target:/lib64/libc.so.6
#2  0x00007fa674629f0a in slapi_rwlock_rdlock (rwlock=<optimized out>) at ldap/servers/slapd/slapi2runtime.c:288
#3  dse_get_entry_copy (pdse=0x7fa67302dc20, dn=0x7fa3056aa160, use_lock=<optimized out>) at ldap/servers/slapd/dse.c:196
#4  0x00007fa67462b958 in dse_search (pb=0x7fa3056e76e0) at ldap/servers/slapd/dse.c:1681
#5  0x00007fa674671eb4 in op_shared_search (pb=pb@entry=0x7fa3056e76e0, send_result=send_result@entry=1) at ldap/servers/slapd/opshared.c:843
#6  0x00005563a2dee3e9 in do_search (pb=0x7fa3056e76e0) at ldap/servers/slapd/search.c:410
#7  0x00005563a2ddb8f2 in connection_dispatch_operation (conn=<optimized out>, op=<optimized out>, pb=<optimized out>) at ldap/servers/slapd/connection.c:678
#8  connection_threadmain (arg=<optimized out>) at ldap/servers/slapd/connection.c:1921
#9  0x00007fa673de13b7 in _pt_root () at target:/lib64/libnspr4.so
#10 0x00007fa67447e797 in start_thread () at target:/lib64/libc.so.6
#11 0x00007fa67450278c in __clone3 () at target:/lib64/libc.so.6

**Comment by mayurcrunchr** [comment]
awesome digging @vashirov . Is there a setting/parameter I could use to prevent this situation from happening until the issue is resolved?

**Comment by mayurcrunchr** [comment]
@vashirov any plans to fix it? We are currently blocked by this and have disabled backups in production. This is impacting out ability to reliably restore our application to a previous historically working state. Any workaround would also be appreciated in case the fix is not planned for the near future

**Comment by vashirov** [comment]
@mayurcrunchr unfortunately, there is no workaround. We plan to start working on it this month, so please stay tuned.

**Comment by mayurcrunchr** [comment]
thanks @vashirov . Will keep an eye on updates.

**Comment by progier389** [comment]
FYI: the regression introduced by commit 0f9a80ac65bd33ca69474950aab83e2d0d7eb38b in version 2.4.1

**Comment by progier389** [comment]
0c6913407..7e98ab343  main -> main
   0de8c2144..1e4ce02d2  389-ds-base-3.0 -> 389-ds-base-3.0
   2ecd3921e..65942b509  389-ds-base-2.5 -> 389-ds-base-2.5
   f44d9997f..6697b5882  389-ds-base-2.4 -> 389-ds-base-2.4

**Comment by vashirov** [comment]
@progier389 could you please also backport it to 2.6?

**Comment by progier389** [comment]
Done. Looks like I forgot once again the git fetch --all to get the new branches ! :frowning:

**Comment by mayurcrunchr** [comment]
@vashirov @progier389 @Firstyear could you also publish a new docker image at https://hub.docker.com/r/389ds/dirsrv/. we are currently running ldap in a docker container

**Comment by vashirov** [comment]
Once we cut a new release, it should appear there.

**Comment by mayurcrunchr** [comment]
@vashirov one more thing we wanted to know is when is the new release scheduled? We wanted to check if we can wait till the solution is available or create a temporary workaround around it(restarting the docker container) to make it work for now

**Comment by vashirov** [comment]
Should be released this week, worst case by the end of the month.

**Comment by vashirov** [comment]
@progier389 after this commit backup tests started to fail in 3.0:
https://github.com/389ds/389-ds-base/actions/runs/12650325366/job/35250352696

I will run more tests with the sanitized build.

**Comment by progier389** [comment]
Indeed a core is spawned.
```
#0  PR_CloseDir (dir=dir@entry=0x0) at ../../../../nspr/pr/src/pthreads/ptio.c:3729
#1  0x00007f1f37d5f9d3 in ldbm_archive_config (bakdir=<optimized out>, task=0x7f1bcae1df00) at ldap/servers/slapd/back-ldbm/archive.c:730
#2  0x00007f1f37ddde7b in dbmdb_backup (li=0x7f1f3aac8080, dest_dir=0x7f1bcae14390 "/var/lib/dirsrv/slapd-standalone1/bak/bak1", task=0x7f1bcae1df00)
    at ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:982
#3  0x00007f1f37d6693a in ldbm_back_ldbm2archive (pb=<optimized out>) at ldap/servers/slapd/back-ldbm/archive.c:423
#4  0x00007f1f3c8ce31b in task_backup_thread (arg=0x7f1bcadfd060) at ldap/servers/slapd/task.c:1501
#5  0x00007f1f3be7f3b7 in _pt_root (arg=0x7f1bcae22000) at ../../../../nspr/pr/src/pthreads/ptthread.c:191
#6  0x00007f1f3c608057 in start_thread (arg=<optimized out>) at pthread_create.c:448
#7  0x00007f1f3c68bf4c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
That is a bit weird as the original  fix should not impact the closedir.
 Maybe a cherry-pick issue (merge issue or a missing fix issue) ?

**Comment by progier389** [comment]
It looks like a commit that checks that dir handle is not NULL is missing:
04a0b6ac776a1d588ec2e10ff651e5015078ad21 Issue 6229 - After an initial failure, subsequent online backups fail (#6230)
Will cherry pick issue #6229

**Comment by vashirov** [comment]
Nice catch, thank you @progier389!
