### ISSUE TITLE
UI - clicking on a database suffix under the Monitor tab crashes UI 

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6429]
**Issue Description**

Crash happens on mdb instance as "dn cache" does not exist.

To reproduce click on:   Monitor -> Database -> SUFFIX

```
suffixMonitor.jsx:170 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Function.<anonymous> (suffixMonitor.jsx:170:50)
    at process_queue (cockpit.js:1311:37)
    at cockpit.js:1324:35
    at later_drain (cockpit.js:1205:13)


monitor/suffixMonitor.jsx:

    const dnratio = config.attrs.dncachehitratio[0];

```

**Comment by mreynolds389** [comment]
Fixed via a different ticket, closing.

**Comment by jchapma** [comment]
2f42fc2eb..d119e818e  389-ds-base-3.0 -> 389-ds-base-3.0
